/*
 * Copyright 2019-present HiveMQ GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.hivemq.protocols.v2.config;

import com.hivemq.adapter.sdk.api.v2.node.AccessFlags;
import com.hivemq.adapter.sdk.api.v2.node.AccessTriState;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * The declared access capabilities of a tag's node in the {@code <v2>} section — the
 * config-side mirror of the SDK {@link AccessFlags}, generated by external tooling and only read by Edge. Each
 * attribute is an {@link AccessTriState} ({@code YES} / {@code NO} / {@code WILL_NOT_USE}); when the {@code <access>}
 * element is omitted every flag defaults to {@link AccessTriState#NO} (no declared capability).
 */
@SuppressWarnings({"FieldMayBeFinal", "unused"})
@XmlAccessorType(XmlAccessType.NONE)
// Distinct XML type name to keep the JAXB context's type registry collision-free.
@XmlType(name = "v2AccessFlagsEntity")
public class AccessFlagsEntity {

    @XmlAttribute(name = "readable")
    private @NotNull AccessTriState readable = AccessTriState.NO;

    @XmlAttribute(name = "writable")
    private @NotNull AccessTriState writable = AccessTriState.NO;

    @XmlAttribute(name = "pollable")
    private @NotNull AccessTriState pollable = AccessTriState.NO;

    @XmlAttribute(name = "subscribable")
    private @NotNull AccessTriState subscribable = AccessTriState.NO;

    // no-arg constructor for JAXB; field initializers carry the defaults
    public AccessFlagsEntity() {}

    public AccessFlagsEntity(
            final @NotNull AccessTriState readable,
            final @NotNull AccessTriState writable,
            final @NotNull AccessTriState pollable,
            final @NotNull AccessTriState subscribable) {
        this.readable = readable;
        this.writable = writable;
        this.pollable = pollable;
        this.subscribable = subscribable;
    }

    public @NotNull AccessTriState getReadable() {
        return readable;
    }

    public @NotNull AccessTriState getWritable() {
        return writable;
    }

    public @NotNull AccessTriState getPollable() {
        return pollable;
    }

    public @NotNull AccessTriState getSubscribable() {
        return subscribable;
    }

    /**
     * @return the reused SDK {@link AccessFlags} this config entry describes.
     */
    public @NotNull AccessFlags toAccessFlags() {
        return new AccessFlags(readable, writable, pollable, subscribable);
    }

    @Override
    public boolean equals(final @Nullable Object o) {
        if (o instanceof final AccessFlagsEntity that) {
            return readable == that.readable
                    && writable == that.writable
                    && pollable == that.pollable
                    && subscribable == that.subscribable;
        }
        return false;
    }

    @Override
    public int hashCode() {
        return Objects.hash(readable, writable, pollable, subscribable);
    }
}
