/*
 * Copyright 2019-present HiveMQ GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.hivemq.protocols.v2.config;

import com.hivemq.configuration.entity.EntityValidatable;
import com.hivemq.protocols.v2.runtime.RetryPolicy;
import jakarta.xml.bind.ValidationEvent;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import java.util.List;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * The exponential-backoff retry policy for an adapter, in the {@code <v2>} section — the config-side mirror of the runtime {@link RetryPolicy}. Carried on the {@code <retry-policy>} element as
 * four attributes; when the element is omitted the {@link RetryPolicy#defaults() framework defaults} apply. Edge only
 * reads this; it is generated by external tooling.
 */
@SuppressWarnings({"FieldMayBeFinal", "unused"})
@XmlAccessorType(XmlAccessType.NONE)
// Distinct XML type name to keep the JAXB context's type registry collision-free.
@XmlType(name = "v2RetryPolicyEntity")
public class RetryPolicyEntity implements EntityValidatable {

    private static final @NotNull RetryPolicy DEFAULTS = RetryPolicy.defaults();

    @XmlAttribute(name = "initial-millis")
    private long initialMillis = DEFAULTS.initialMillis();

    @XmlAttribute(name = "factor")
    private double factor = DEFAULTS.factor();

    @XmlAttribute(name = "ceiling-millis")
    private long ceilingMillis = DEFAULTS.ceilingMillis();

    @XmlAttribute(name = "maximum-retries")
    private int maximumRetries = DEFAULTS.maximumRetries();

    // no-arg constructor for JAXB; field initializers carry the defaults
    public RetryPolicyEntity() {}

    public RetryPolicyEntity(
            final long initialMillis, final double factor, final long ceilingMillis, final int maximumRetries) {
        this.initialMillis = initialMillis;
        this.factor = factor;
        this.ceilingMillis = ceilingMillis;
        this.maximumRetries = maximumRetries;
    }

    public long getInitialMillis() {
        return initialMillis;
    }

    public double getFactor() {
        return factor;
    }

    public long getCeilingMillis() {
        return ceilingMillis;
    }

    public int getMaximumRetries() {
        return maximumRetries;
    }

    /**
     * @return the runtime {@link RetryPolicy} this config entry describes.
     * @throws IllegalArgumentException if the values violate the {@link RetryPolicy} invariants. Callers should
     *         {@link #validate(List) validate} first so a bad config is rejected at load with a clear message.
     */
    public @NotNull RetryPolicy toRetryPolicy() {
        return new RetryPolicy(initialMillis, factor, ceilingMillis, maximumRetries);
    }

    @Override
    public void validate(final @NotNull List<ValidationEvent> validationEvents) {
        EntityValidatable.notMatch(
                validationEvents,
                () -> initialMillis > 0,
                () -> "retry-policy initial-millis (" + initialMillis + ") must be positive");
        EntityValidatable.notMatch(
                validationEvents, () -> factor >= 1.0, () -> "retry-policy factor (" + factor + ") must be at least 1");
        EntityValidatable.notMatch(
                validationEvents,
                () -> ceilingMillis >= initialMillis,
                () -> "retry-policy ceiling-millis ("
                        + ceilingMillis
                        + ") must be at least initial-millis ("
                        + initialMillis
                        + ")");
        EntityValidatable.notMatch(
                validationEvents,
                () -> maximumRetries >= 0,
                () -> "retry-policy maximum-retries (" + maximumRetries + ") must not be negative");
    }

    @Override
    public boolean equals(final @Nullable Object o) {
        if (o instanceof final RetryPolicyEntity that) {
            return initialMillis == that.initialMillis
                    && Double.compare(factor, that.factor) == 0
                    && ceilingMillis == that.ceilingMillis
                    && maximumRetries == that.maximumRetries;
        }
        return false;
    }

    @Override
    public int hashCode() {
        return Objects.hash(initialMillis, factor, ceilingMillis, maximumRetries);
    }
}
