/*
 * Copyright 2019-present HiveMQ GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.hivemq.protocols.v2.config;

import com.hivemq.adapter.sdk.api.v2.node.AccessTriState;
import com.hivemq.configuration.entity.EntityValidatable;
import jakarta.xml.bind.ValidationEvent;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.helpers.ValidationEventImpl;
import java.util.List;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * A tag in the {@code <v2>} section — one node the adapter exposes, plus the persisted
 * per-aspect activation preferences that carry the tag lifecycle (D7). The {@code node-string} is the opaque
 * JSON node definition, stored as-is and round-tripped to the adapter unchanged. {@code read-activated} and
 * {@code write-activated} default to {@code true} when absent; a reload that flips only these flags is an
 * {@code ACTIVATION_ONLY} change applied without reconnecting. Edge only reads this section; it is generated by
 * external tooling.
 */
@SuppressWarnings({"FieldMayBeFinal", "unused"})
@XmlAccessorType(XmlAccessType.NONE)
// Distinct XML type name so the JAXB context can host this beside the identically-named legacy
// com.hivemq.configuration.entity.adapter.TagEntity without a type-name collision.
@XmlType(name = "v2TagEntity")
public class TagEntity implements EntityValidatable {

    private static final long DEFAULT_POLL_INTERVAL_MILLIS = 5000;

    @XmlElement(name = "name", required = true)
    private @NotNull String name = "";

    @XmlElement(name = "node-string", required = true)
    private @NotNull String nodeString = "";

    @XmlElement(name = "read-activated", defaultValue = "true")
    private boolean readActivated = true;

    @XmlElement(name = "write-activated", defaultValue = "true")
    private boolean writeActivated = true;

    @XmlElement(name = "pollable")
    private boolean pollable = false;

    @XmlElement(name = "subscribable")
    private boolean subscribable = false;

    @XmlElement(name = "poll-interval-millis")
    private long pollIntervalMillis = DEFAULT_POLL_INTERVAL_MILLIS;

    // Omitted <access> = no access declaration = unconstrained. An explicit element (whose per-attribute defaults
    // are NO) is the declared model and is enforced at runtime (EDG-824 #14).
    @XmlElement(name = "access")
    private @NotNull AccessFlagsEntity access = AccessFlagsEntity.unrestricted();

    // no-arg constructor for JAXB; field initializers carry the defaults
    public TagEntity() {}

    public TagEntity(
            final @NotNull String name,
            final @NotNull String nodeString,
            final boolean readActivated,
            final boolean writeActivated,
            final boolean pollable,
            final boolean subscribable,
            final long pollIntervalMillis,
            final @NotNull AccessFlagsEntity access) {
        this.name = name;
        this.nodeString = nodeString;
        this.readActivated = readActivated;
        this.writeActivated = writeActivated;
        this.pollable = pollable;
        this.subscribable = subscribable;
        this.pollIntervalMillis = pollIntervalMillis;
        this.access = access;
    }

    public @NotNull String getName() {
        return name;
    }

    public @NotNull String getNodeString() {
        return nodeString;
    }

    public boolean isReadActivated() {
        return readActivated;
    }

    public boolean isWriteActivated() {
        return writeActivated;
    }

    public boolean isPollable() {
        return pollable;
    }

    public boolean isSubscribable() {
        return subscribable;
    }

    public long getPollIntervalMillis() {
        return pollIntervalMillis;
    }

    public @NotNull AccessFlagsEntity getAccess() {
        return access;
    }

    @Override
    public void validate(final @NotNull List<ValidationEvent> validationEvents) {
        EntityValidatable.notEmpty(validationEvents, name, "tag name");
        EntityValidatable.notEmpty(validationEvents, nodeString, "tag [" + name + "] node-string");
        EntityValidatable.notMatch(
                validationEvents,
                () -> pollIntervalMillis > 0,
                () -> "tag [" + name + "] poll-interval-millis (" + pollIntervalMillis + ") must be positive");
    }

    /**
     * Warn when this tag's activation contradicts its own {@code <access>} flags (EDG-824 #14): the access model is
     * enforced at runtime, so an activated aspect with no permitted capability silently never operates. That has to
     * be a deliberate choice, not a typo, so the contradiction is surfaced rather than left to be discovered as
     * missing data. An omitted {@code <access>} element is unrestricted (all flags YES) and can never trip this;
     * only an explicit element — whose omitted child attributes default to NO — can.
     * <p>
     * Every rule here reads this tag alone, so it belongs on the tag rather than on the adapter (review suggestion
     * on #1635). It is kept out of {@link #validate} because the {@code adapterId} is not the tag's to know, and
     * dropping it would leave warnings that cannot be traced to an adapter once two of them declare the same tag
     * name — the {@link EntityValidatable} contract fixes {@code validate}'s signature, so it arrives as a
     * parameter here instead.
     *
     * @param validationEvents the collector the owning adapter is validating into.
     * @param adapterId        the owning adapter's id, for the operator-facing message.
     */
    public void validateAccessContradictions(
            final @NotNull List<ValidationEvent> validationEvents, final @NotNull String adapterId) {
        final boolean readPermitted = access.getReadable() == AccessTriState.YES
                && ((pollable && access.getPollable() == AccessTriState.YES)
                        || (subscribable && access.getSubscribable() == AccessTriState.YES));
        if (readActivated && !readPermitted) {
            validationEvents.add(new ValidationEventImpl(
                    ValidationEvent.WARNING,
                    "adapter [" + adapterId + "] tag [" + name
                            + "] is read-activated but its <access> flags permit no read transport;"
                            + " the tag will never be read",
                    null));
        }
        if (writeActivated && access.getWritable() != AccessTriState.YES) {
            validationEvents.add(new ValidationEventImpl(
                    ValidationEvent.WARNING,
                    "adapter [" + adapterId + "] tag [" + name
                            + "] is write-activated but its <access> flags do not permit writing;"
                            + " the tag will never be written",
                    null));
        }
    }

    @Override
    public boolean equals(final @Nullable Object o) {
        if (o instanceof final TagEntity that) {
            return readActivated == that.readActivated
                    && writeActivated == that.writeActivated
                    && pollable == that.pollable
                    && subscribable == that.subscribable
                    && pollIntervalMillis == that.pollIntervalMillis
                    && Objects.equals(name, that.name)
                    && Objects.equals(nodeString, that.nodeString)
                    && Objects.equals(access, that.access);
        }
        return false;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                name, nodeString, readActivated, writeActivated, pollable, subscribable, pollIntervalMillis, access);
    }
}
