//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.hivemq.edge.adapters.mtconnect.schemas.error.error_1_3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The coordinate system to be used for the position
 * 
 * <p>Java class for CoordinateSystemType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="CoordinateSystemType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="MACHINE"/>
 *     <enumeration value="WORK"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@com.fasterxml.jackson.annotation.JsonTypeName(value = "CoordinateSystemType")
@XmlType(name = "CoordinateSystemType")
@XmlEnum
public enum CoordinateSystemType {

    MACHINE,
    WORK;

    public String value() {
        return name();
    }

    public static CoordinateSystemType fromValue(String v) {
        return valueOf(v);
    }

}
