= HiveMQ Edge Contributing Guidelines

== Introduction

Anyone is welcome to participate and contribute to the HiveMQ open source community.
We encourage people to use the https://github.com/hivemq/hivemq-edge/issues[Github issue tracker] and create pull requests.
The scope of HiveMQ Edge is to provide

. a high-quality implementation of the MQTT broker specification, and
. the extension framework enabling the integration of HiveMQ Edge into other applications, and
. the proctocol adapter framework enabling the translation of other protocols into MQTT based workloads.

Therefore, we ask that contributions are focused on improving the current implementation and project scope.

We will not accept contributions that would add features that expand the scope of the project.
It is HiveMQ’s intention to offer commercial products that will add features suited for enterprise deployments of HiveMQ, such as clustering, monitoring tools, enterprise security, technical support, and more.
We also expect that other companies and open source projects will create extensions of HiveMQ Edge to suit their specific customer requirements.
If you would like to suggest a new feature, please contact the project team (support@hivemq.com) to discuss if it fits within the project scope.
If you wish to contribute, we will accept primarily Bug Fixes, Typos, Documentation, JavaDoc and Logging.

== Licensing

HiveMQ Edge is released under the Apache 2.0 license to allow you the use of the software as you please.
By contributing your code, you agree to license your contribution under the terms of the Apache License, Version 2.0.

Please fill out our Contributor License Agreement (CLA), otherwise we cannot accept your contribution.

All files must contain the license header from the link:hivemq-edge/HEADER[header file].

== Contributor License Agreement

If you wish to contribute to HiveMQ Edge, please fill out and sign the https://na4.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=84cc1040-8db3-4598-b7fa-d5618b7eaa59&env=na4&acct=5c4e7f8f-440b-424c-ada4-aef44fd4456b&v=2[Contributor License Agreement].
Please read this document carefully before signing it and keep a copy for your own records.
Once we've received your signed CLA, you will be added to the list of contributors and our HiveMQ Development Team will review your contributions.

In case the rights to all intellectual property created by you are maintained by your employer, including your work on HiveMQ CE, you must ensure you have retained all rights to grant the license, or that your employer has agreed to a separate https://www.hivemq.com/downloads/Corporate_Contributor_License_Agreement.pdf[Corporate CLA].

== Contribution Guidelines

=== Issues

==== Bug Fixes and Minor Features

Please always open an issue in the issue tracker before sending a pull request and wait until someone from the HiveMQ Development Team approves it, before you start working on it.
This prevents you from working on issues that we will ultimately not accept.
When you start working on an approved issue, please make it known in the comments that you are going to work on it, so a simultaneous contribution by someone else can be avoided.

After you commit, your contribution will be reviewed by the HiveMQ Development Team.
We reserve the right to release only reviewed and approved implementations.

==== Security Issues

Please do not report any security issue to the public issue tracker.
Please send security issues directly to security@hivemq.com.

==== Questions

Please refer all your questions about HiveMQ Edge to the https://community.hivemq.com[HiveMQ Community Forum].

Issues consisting of questions or suggestions will be closed immediately.

=== Checking out the Project

We recommend that you use the https://www.jetbrains.com/idea/download/[IntelliJ] IDE for all development on HiveMQ CE.
It will automate your process as much as possible.
Java version 11 is required to build and run HiveMQ Edge (we recommend OpenJDK 11).
You can check your installed Java version by entering `java -version` on the command line.

First you need to https://help.github.com/en/articles/fork-a-repo[fork] HiveMQ Edge https://github.com/hivemq/hivemq-edge[repository].

Then you can clone the repository:

[source,bash]
----
git clone https://github.com/<your user name>/hivemq-edge.git
----

*Open* the HiveMQ Edge project folder in IntelliJ.
Choose to sync the gradle project, if so prompted by the IDE.
After setting the gradle and project SDK (Java 11), you are good to go.

=== Checking out the HiveMQ Extension SDK

HiveMQ Edge uses the HiveMQ Extension SDK which resides in https://github.com/hivemq/hivemq-extension-sdk[its own repository]. And the HiveMQ Edge Extension SDK which can be found https://github.com/hivemq/hivemq-edge-extension-sdk[here].
By default, you can not use the latest changes of or modify the Extension SDK.
Please checkout the `hivemq-extension-sdk` repository next to the `hivemq-edge` repository.
Gradle and IntelliJ will then automatically wire the two projects.

If you only want to use the Extension SDK, execute the following command from the `hivemq-edge` project directory:

----
git clone https://github.com/hivemq/hivemq-extension-sdk.git ../hivemq-extension-sdk
git clone https://github.com/hivemq/hivemq-edge-extension-sdk.git ../hivemq-edge-extension-sdk
----

If you also want to make changes to the Extension SDK, please fork the `hivemq-extension-sdk` repository and clone your fork:

----
git clone https://github.com/<your user name>/hivemq-extension-sdk.git ../hivemq-extension-sdk
git clone https://github.com/<your user name>/hivemq-edge-extension-sdk.git ../hivemq-edge-extension-sdk
----

=== Branching Model

A modified version of https://nvie.com/posts/a-successful-git-branching-model/[git-flow] is used for the structuring of the HiveMQ Edge repository.

All branches must start with an issue type tag, usually `bugfix` or `improvement`, followed by a slash `/` and a __speaking name__ describing the code change e.g. `bugfix/locking-for-concurrent-access-in-some-class` or `improvement/better-javadoc-in-some-interface`.
The pull requests must be opened against the `master` branch.

=== Code Style Guidelines

Only code following _good_ Java practices, like using the appropriate keywords and visibility, will be accepted.

HiveMQ Edge uses nullability annotations, these should be used to annotate the declared types of variables and fields, whose initialization status can be in question.

.Nullability example
[source,java]
----
class SomeClass {

    // this must never be null, the accessor can depend on it
    private @NotNull SomeType myField;

    // this may be null, the accessor must check
    private @Nullable SomeType anotherField;

}
----

The following annotations are provided for this purpose:

.@Nullable
----
com.hivemq.extension.sdk.api.annotations.NotNull
com.hivemq.extension.sdk.api.annotations.Nullable
----

=== Commit Guidelines

You can set up IntelliJ to recognise these annotations under `Preferences > Inspections > @NotNull/@Nullable problems > Configure annotations`.

Please watch out for this inspection and check the _Reformat code_, _Optimize imports_ and _Perform code analysis_ checkboxes in the commit dialogue.

=== Testing

The HiveMQ Edge project only accepts pull requests that contain unit tests and have sufficient unit test coverage.

=== Pull Requests

As soon as your code is ready for a https://help.github.com/en/articles/creating-a-pull-request[pull request], please link the specific issue that you want to resolve.
Once the continuous integration is successful and at least one member of the HiveMQ Development Team has approved the changes, you will be asked to rebase and squash before the pull request can be merged.

We greatly appreciate your involvement and contribution.
