//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.hivemq.edge.adapters.mtconnect.schemas.devices.devices_1_8;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * {{block(Auxiliary)}} is an abstract {{block(Component)}} that represents
 *         removable part(s) of a piece of equipment providing supplementary or
 *         extended functionality.
 * 
 * <p>Java class for AuxiliaryType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="AuxiliaryType">
 *   <complexContent>
 *     <extension base="{urn:mtconnect.org:MTConnectDevices:1.8}CommonComponentType">
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@com.fasterxml.jackson.annotation.JsonTypeName(value = "AuxiliaryType")
@XmlType(name = "AuxiliaryType")
@XmlSeeAlso({
    LoaderType.class,
    SensorType.class,
    WasteDisposalType.class,
    ToolingDeliveryType.class
})
public class AuxiliaryType
    extends CommonComponentType
{


}
