//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.hivemq.edge.adapters.mtconnect.schemas.devices.devices_1_8;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * An abstract component that has an optional uuid
 * 
 * <p>Java class for CommonComponentType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="CommonComponentType">
 *   <complexContent>
 *     <extension base="{urn:mtconnect.org:MTConnectDevices:1.8}ComponentType">
 *       <attribute name="uuid" type="{urn:mtconnect.org:MTConnectDevices:1.8}UuidType" />
 *       <attribute name="name" type="{urn:mtconnect.org:MTConnectDevices:1.8}NameType" />
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@com.fasterxml.jackson.annotation.JsonTypeName(value = "CommonComponentType")
@XmlType(name = "CommonComponentType")
@XmlSeeAlso({
    ActuatorType.class,
    ChuckType.class,
    DoorType.class,
    InterfaceType.class,
    PathType.class,
    PowerType.class,
    AxisType.class,
    ResourceType.class,
    StructureType.class,
    PartType.class,
    AdapterType.class,
    AuxiliaryType.class,
    OrganizerType.class,
    ProcessType.class,
    SystemType.class,
    LockType.class,
    StructuresType.class,
    AxesType.class,
    InterfacesType.class,
    SystemsType.class,
    ResourcesType.class,
    AuxiliariesType.class,
    ProcessesType.class,
    AdaptersType.class,
    PartsType.class,
    MaterialsType.class
})
public class CommonComponentType
    extends ComponentType
{

    /**
     * The component's universally unique id.
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "uuid")
    @XmlAttribute(name = "uuid")
    protected String uuid;
    /**
     * The component's name
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "name")
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * The component's universally unique id.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getUuid()
     */
    public void setUuid(String value) {
        this.uuid = value;
    }

    /**
     * The component's name
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getName()
     */
    public void setName(String value) {
        this.name = value;
    }

}
