//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.hivemq.edge.adapters.mtconnect.schemas.devices.devices_1_8;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * {{block(System)}} is an abstract {{block(Component)}} that represents
 *         part(s) of a piece of equipment that is permanently integrated into the
 *         piece of equipment.
 * 
 * <p>Java class for SystemType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="SystemType">
 *   <complexContent>
 *     <extension base="{urn:mtconnect.org:MTConnectDevices:1.8}CommonComponentType">
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@com.fasterxml.jackson.annotation.JsonTypeName(value = "SystemType")
@XmlType(name = "SystemType")
@XmlSeeAlso({
    ControllerType.class,
    CoolantType.class,
    DepositionType.class,
    DielectricType.class,
    ElectricType.class,
    EnclosureType.class,
    EndEffectorType.class,
    FeederType.class,
    HydraulicType.class,
    LubricationType.class,
    PneumaticType.class,
    ProcessPowerType.class,
    ProtectiveType.class,
    WorkEnvelopeType.class,
    EnvironmentalType.class
})
public class SystemType
    extends CommonComponentType
{


}
