//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.hivemq.edge.adapters.mtconnect.schemas.devices.devices_1_2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * An abstract component that has an optional uuid
 * 
 * <p>Java class for CommonComponentType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="CommonComponentType">
 *   <complexContent>
 *     <extension base="{urn:mtconnect.org:MTConnectDevices:1.2}ComponentType">
 *       <attribute name="uuid" type="{urn:mtconnect.org:MTConnectDevices:1.2}UuidType" />
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@com.fasterxml.jackson.annotation.JsonTypeName(value = "CommonComponentType")
@XmlType(name = "CommonComponentType")
@XmlSeeAlso({
    ControllerType.class,
    PowerType.class,
    SensorType.class,
    PathType.class,
    ActuatorType.class,
    DoorType.class,
    AxesType.class,
    AxisType.class,
    SystemsType.class,
    SystemType.class
})
public class CommonComponentType
    extends ComponentType
{

    @com.fasterxml.jackson.annotation.JsonProperty(value = "uuid")
    @XmlAttribute(name = "uuid")
    protected String uuid;

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUuid(String value) {
        this.uuid = value;
    }

}
