//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.hivemq.edge.adapters.mtconnect.schemas.error.error_1_5;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * An error, XML element, occurs while interpreting a request for
 *         information from a client software application or when an agent
 *         experiences an error while publishing the response to a request for
 *         information.
 * 
 * <p>Java class for ErrorType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ErrorType">
 *   <simpleContent>
 *     <extension base="<urn:mtconnect.org:MTConnectError:1.5>ErrorDescriptionType">
 *       <attribute name="errorCode" use="required" type="{urn:mtconnect.org:MTConnectError:1.5}ErrorCodeType" />
 *     </extension>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@com.fasterxml.jackson.annotation.JsonTypeName(value = "ErrorType")
@XmlType(name = "ErrorType", propOrder = {
    "value"
})
public class ErrorType {

    /**
     * The text description of the error
     * 
     */
    @XmlValue
    protected String value;
    /**
     * Provides a descriptive code that indicates the type of error that
     *               was encountered by an agent.
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "errorCode")
    @XmlAttribute(name = "errorCode", required = true)
    protected ErrorCodeType errorCode;

    /**
     * The text description of the error
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getValue()
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Provides a descriptive code that indicates the type of error that
     *               was encountered by an agent.
     * 
     * @return
     *     possible object is
     *     {@link ErrorCodeType }
     *     
     */
    public ErrorCodeType getErrorCode() {
        return errorCode;
    }

    /**
     * Sets the value of the errorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorCodeType }
     *     
     * @see #getErrorCode()
     */
    public void setErrorCode(ErrorCodeType value) {
        this.errorCode = value;
    }

}
