//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.hivemq.edge.adapters.mtconnect.schemas.streams.streams_1_1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * An abstract event
 * 
 * <p>Java class for EventType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="EventType">
 *   <simpleContent>
 *     <extension base="<urn:mtconnect.org:MTConnectStreams:1.1>ResultType">
 *     </extension>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@com.fasterxml.jackson.annotation.JsonTypeName(value = "EventType")
@XmlType(name = "EventType")
@XmlSeeAlso({
    CodeType.class,
    BlockType.class,
    LineType.class,
    PowerStatusType.class,
    PartCountType.class,
    DirectionType.class,
    ProgramType.class,
    ExecutionType.class,
    ControllerModeType.class,
    ToolIdType.class,
    PartIdType.class,
    DoorStateType.class,
    WorkholdingIdType.class,
    RotaryModeType.class,
    ActiveAxesType.class,
    CoupledAxesType.class,
    AxesCouplingType.class,
    MessageType.class,
    EmergencyStopType.class,
    AvailabilityType.class,
    PathModeType.class,
    PowerStateType.class,
    AlarmType.class,
    AxisCouplingType.class
})
public abstract class EventType
    extends ResultType
{


}
