/*
 * Copyright 2019-present HiveMQ GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.hivemq.protocols.v2.wrapper;

/**
 * The persisted per-aspect activation preference for one tag: whether the tag's read
 * aspect and write aspect are activated. These are the {@code read-activated} / {@code write-activated} flags
 * from the {@code <v2-protocol-adapters>} configuration section — generated by external tooling and applied at
 * startup and on reload, never set through REST.
 * <p>
 * One of the three conditions of the three-condition rule (direction activated ∧ aspect activated ∧ used); the
 * other two are the adapter direction goal and the {@code used} derivation.
 *
 * @param readActivated  whether the tag's read aspect is activated in the configuration.
 * @param writeActivated whether the tag's write aspect is activated in the configuration.
 */
public record TagAspectActivationPreference(boolean readActivated, boolean writeActivated) {

    /**
     * @return the default activation: both aspects activated (the configuration default when the flags are
     *         absent).
     */
    public static TagAspectActivationPreference defaults() {
        return new TagAspectActivationPreference(true, true);
    }
}
