//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.hivemq.edge.adapters.mtconnect.schemas.assets.assets_1_6;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The type of tool location
 * 
 * <p>Java class for LocationsTypeType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="LocationsTypeType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="POT"/>
 *     <enumeration value="STATION"/>
 *     <enumeration value="CRIB"/>
 *     <enumeration value="STANDBY"/>
 *     <enumeration value="SPINDLE"/>
 *     <enumeration value="REJECT"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@com.fasterxml.jackson.annotation.JsonTypeName(value = "LocationsTypeType")
@XmlType(name = "LocationsTypeType")
@XmlEnum
public enum LocationsTypeType {


    /**
     * Pot location of tool
     * 
     */
    POT,

    /**
     * The station on a turning machine
     * 
     */
    STATION,

    /**
     * The crib location of the tool
     * 
     */
    CRIB,

    /**
     * The tool is ready to be used
     * 
     */
    STANDBY,

    /**
     * The spindle the tool currently resides in
     * 
     */
    SPINDLE,

    /**
     * The tool is in a reject pot location
     * 
     */
    REJECT;

    public String value() {
        return name();
    }

    public static LocationsTypeType fromValue(String v) {
        return valueOf(v);
    }

}
