type: object
description: websocketConfiguration associated with the bridge
nullable: true
properties:
  enabled:
    type: boolean
    default: false
    description: If Websockets are used
  serverPath:
    type: string
    default: /mqtt
    description: >-
      The server path used by the bridge client. This must be setup as path at
      the remote broker
  subProtocol:
    type: string
    default: mqtt
    description: >-
      The sub-protocol used by the bridge client. This must be supported by the
      remote broker
