//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.hivemq.edge.adapters.mtconnect.schemas.streams.streams_1_7;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * An unfaceted string event
 * 
 * <p>Java class for StringEventType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="StringEventType">
 *   <simpleContent>
 *     <restriction base="<urn:mtconnect.org:MTConnectStreams:1.7>EventType">
 *     </restriction>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@com.fasterxml.jackson.annotation.JsonTypeName(value = "StringEventType")
@XmlType(name = "StringEventType")
@XmlSeeAlso({
    AssetChangedType.class,
    AssetRemovedType.class,
    CloseChuckType.class,
    CloseDoorType.class,
    CodeType.class,
    CompositionStateType.class,
    DateCodeType.class,
    DeviceUuidType.class,
    DirectionType.class,
    LineType.class,
    LineLabelType.class,
    MaterialType.class,
    MaterialChangeType.class,
    MaterialFeedType.class,
    MaterialLoadType.class,
    MaterialRetractType.class,
    MaterialUnloadType.class,
    OpenChuckType.class,
    OpenDoorType.class,
    OperatorIdType.class,
    PartChangeType.class,
    PartIdType.class,
    PartNumberType.class,
    PowerStatusType.class,
    ProcessTimeType.class,
    ProgramType.class,
    ProgramCommentType.class,
    ProgramEditNameType.class,
    ProgramHeaderType.class,
    ProgramLocationType.class,
    ProgramLocationTypeType.class,
    SerialNumberType.class,
    ToolGroupType.class,
    UserType.class,
    VariableType.class,
    WireType.class,
    WorkholdingIdType.class,
    OperatingSystemType.class,
    FirmwareType.class,
    ApplicationType.class,
    LibraryType.class,
    HardwareType.class,
    NetworkType.class,
    RotationType.class,
    TranslationType.class,
    ProcessKindIdType.class,
    AlarmLimitType.class,
    ProcessAggregateIdType.class,
    PartKindIdType.class,
    AdapterURIType.class,
    DeviceRemovedType.class,
    DeviceChangedType.class,
    SpecificationLimitType.class,
    AdapterSoftwareVersionType.class,
    SensorAttachmentType.class,
    ControlLimitType.class,
    DeviceAddedType.class,
    MTConnectVersionType.class,
    ProcessOccurrenceIdType.class,
    PartGroupIdType.class,
    PartUniqueIdType.class,
    ToolIdType.class,
    ToolNumberType.class,
    ToolAssetIdType.class,
    PalletIdType.class,
    MessageType.class,
    BlockType.class,
    AlarmType.class
})
public class StringEventType
    extends EventType
{


}
