//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.hivemq.edge.adapters.mtconnect.schemas.assets.assets_1_5;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * An abstract mobile asset
 * 
 * <p>Java class for AssetType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="AssetType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <attribute name="assetId" use="required" type="{urn:mtconnect.org:MTConnectAssets:1.5}AssetIdType" />
 *       <attribute name="timestamp" use="required" type="{urn:mtconnect.org:MTConnectAssets:1.5}TimestampType" />
 *       <attribute name="deviceUuid" use="required" type="{urn:mtconnect.org:MTConnectAssets:1.5}UuidType" />
 *       <attribute name="removed" type="{urn:mtconnect.org:MTConnectAssets:1.5}RemovedType" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@com.fasterxml.jackson.annotation.JsonTypeName(value = "AssetType")
@XmlType(name = "AssetType")
@XmlSeeAlso({
    CuttingToolType.class,
    CuttingToolArchetypeType.class
})
public abstract class AssetType {

    /**
     * The unique identifier for the mtconnect asset. The identifier MUST be
     *           unique with respect to all other asset in an MTConnect installation.
     *           The identifier SHOULD be globally unique with respect to all other
     *           asset.
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "assetId")
    @XmlAttribute(name = "assetId", required = true)
    protected String assetId;
    /**
     * The most accurate time available to a piece of equipment that
     *           represents the point in time that the data was reported.
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "timestamp")
    @XmlAttribute(name = "timestamp", required = true)
    protected XMLGregorianCalendar timestamp;
    /**
     * The piece of equipments UUID that supplied this data. This is an
     *           optional element references to the UUID attribute given in the device
     *           element. This can be any series of numbers and letters as defined by
     *           the XML type nmtoken.
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "deviceUuid")
    @XmlAttribute(name = "deviceUuid", required = true)
    protected String deviceUuid;
    /**
     * An indicator that the mtconnect asset has been removed from the piece
     *           of equipment.
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "removed")
    @XmlAttribute(name = "removed")
    protected Boolean removed;

    /**
     * The unique identifier for the mtconnect asset. The identifier MUST be
     *           unique with respect to all other asset in an MTConnect installation.
     *           The identifier SHOULD be globally unique with respect to all other
     *           asset.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetId() {
        return assetId;
    }

    /**
     * Sets the value of the assetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getAssetId()
     */
    public void setAssetId(String value) {
        this.assetId = value;
    }

    /**
     * The most accurate time available to a piece of equipment that
     *           represents the point in time that the data was reported.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     * @see #getTimestamp()
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * The piece of equipments UUID that supplied this data. This is an
     *           optional element references to the UUID attribute given in the device
     *           element. This can be any series of numbers and letters as defined by
     *           the XML type nmtoken.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceUuid() {
        return deviceUuid;
    }

    /**
     * Sets the value of the deviceUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDeviceUuid()
     */
    public void setDeviceUuid(String value) {
        this.deviceUuid = value;
    }

    /**
     * An indicator that the mtconnect asset has been removed from the piece
     *           of equipment.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRemoved() {
        return removed;
    }

    /**
     * Sets the value of the removed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #isRemoved()
     */
    public void setRemoved(Boolean value) {
        this.removed = value;
    }

}
