//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.hivemq.edge.adapters.mtconnect.schemas.devices.devices_1_6;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hivemq.edge.adapters.mtconnect.schemas.devices.devices_1_6 package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _MTConnectDevices_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "MTConnectDevices");
    private static final QName _Component_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Component");
    private static final QName _CommonComponent_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "CommonComponent");
    private static final QName _Device_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Device");
    private static final QName _Actuator_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Actuator");
    private static final QName _Auxiliaries_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Auxiliaries");
    private static final QName _Axes_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Axes");
    private static final QName _Electric_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Electric");
    private static final QName _Systems_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Systems");
    private static final QName _Loader_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Loader");
    private static final QName _WasteDisposal_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "WasteDisposal");
    private static final QName _ToolingDelivery_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "ToolingDelivery");
    private static final QName _Environmental_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Environmental");
    private static final QName _BarFeeder_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "BarFeeder");
    private static final QName _Interface_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Interface");
    private static final QName _Interfaces_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Interfaces");
    private static final QName _Linear_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Linear");
    private static final QName _Path_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Path");
    private static final QName _Controller_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Controller");
    private static final QName _Resources_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Resources");
    private static final QName _Power_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Power");
    private static final QName _Materials_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Materials");
    private static final QName _Stock_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Stock");
    private static final QName _Personnel_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Personnel");
    private static final QName _Rotary_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Rotary");
    private static final QName _Sensor_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Sensor");
    private static final QName _Chuck_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Chuck");
    private static final QName _Door_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Door");
    private static final QName _Hydraulic_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Hydraulic");
    private static final QName _Pneumatic_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Pneumatic");
    private static final QName _Coolant_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Coolant");
    private static final QName _Lubrication_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Lubrication");
    private static final QName _Enclosure_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Enclosure");
    private static final QName _Protective_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Protective");
    private static final QName _ProcessPower_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "ProcessPower");
    private static final QName _Feeder_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Feeder");
    private static final QName _Dielectric_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Dielectric");
    private static final QName _DoorInterface_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "DoorInterface");
    private static final QName _ChuckInterface_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "ChuckInterface");
    private static final QName _BarFeederInterface_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "BarFeederInterface");
    private static final QName _MaterialHandlerInterface_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "MaterialHandlerInterface");
    private static final QName _Deposition_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Deposition");
    private static final QName _EndEffector_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "EndEffector");
    private static final QName _WorkEnvelope_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "WorkEnvelope");
    private static final QName _Reference_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Reference");
    private static final QName _DataItemRef_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "DataItemRef");
    private static final QName _ComponentRef_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "ComponentRef");
    private static final QName _AbstractConfiguration_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "AbstractConfiguration");
    private static final QName _SensorConfiguration_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "SensorConfiguration");
    private static final QName _Specifications_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Specifications");
    private static final QName _AbstractSpecification_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "AbstractSpecification");
    private static final QName _Specification_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Specification");
    private static final QName _SpecificationValue_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "SpecificationValue");
    private static final QName _Constraint_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Constraint");
    private static final QName _Maximum_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Maximum");
    private static final QName _Minimum_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Minimum");
    private static final QName _Nominal_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Nominal");
    private static final QName _Relationships_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Relationships");
    private static final QName _Relationship_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "Relationship");
    private static final QName _ComponentRelationship_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "ComponentRelationship");
    private static final QName _DeviceRelationship_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "DeviceRelationship");
    private static final QName _CoordinateSystems_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "CoordinateSystems");
    private static final QName _CoordinateSystemsTypeCoordinateSystem_QNAME = new QName("urn:mtconnect.org:MTConnectDevices:1.6", "CoordinateSystem");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hivemq.edge.adapters.mtconnect.schemas.devices.devices_1_6
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MTConnectDevicesType }
     * 
     * @return
     *     the new instance of {@link MTConnectDevicesType }
     */
    public MTConnectDevicesType createMTConnectDevicesType() {
        return new MTConnectDevicesType();
    }

    /**
     * Create an instance of {@link CommonComponentType }
     * 
     * @return
     *     the new instance of {@link CommonComponentType }
     */
    public CommonComponentType createCommonComponentType() {
        return new CommonComponentType();
    }

    /**
     * Create an instance of {@link DeviceType }
     * 
     * @return
     *     the new instance of {@link DeviceType }
     */
    public DeviceType createDeviceType() {
        return new DeviceType();
    }

    /**
     * Create an instance of {@link ActuatorType }
     * 
     * @return
     *     the new instance of {@link ActuatorType }
     */
    public ActuatorType createActuatorType() {
        return new ActuatorType();
    }

    /**
     * Create an instance of {@link AuxiliariesType }
     * 
     * @return
     *     the new instance of {@link AuxiliariesType }
     */
    public AuxiliariesType createAuxiliariesType() {
        return new AuxiliariesType();
    }

    /**
     * Create an instance of {@link AxesType }
     * 
     * @return
     *     the new instance of {@link AxesType }
     */
    public AxesType createAxesType() {
        return new AxesType();
    }

    /**
     * Create an instance of {@link ElectricType }
     * 
     * @return
     *     the new instance of {@link ElectricType }
     */
    public ElectricType createElectricType() {
        return new ElectricType();
    }

    /**
     * Create an instance of {@link SystemsType }
     * 
     * @return
     *     the new instance of {@link SystemsType }
     */
    public SystemsType createSystemsType() {
        return new SystemsType();
    }

    /**
     * Create an instance of {@link LoaderType }
     * 
     * @return
     *     the new instance of {@link LoaderType }
     */
    public LoaderType createLoaderType() {
        return new LoaderType();
    }

    /**
     * Create an instance of {@link WasteDisposalType }
     * 
     * @return
     *     the new instance of {@link WasteDisposalType }
     */
    public WasteDisposalType createWasteDisposalType() {
        return new WasteDisposalType();
    }

    /**
     * Create an instance of {@link ToolingDeliveryType }
     * 
     * @return
     *     the new instance of {@link ToolingDeliveryType }
     */
    public ToolingDeliveryType createToolingDeliveryType() {
        return new ToolingDeliveryType();
    }

    /**
     * Create an instance of {@link EnvironmentalType }
     * 
     * @return
     *     the new instance of {@link EnvironmentalType }
     */
    public EnvironmentalType createEnvironmentalType() {
        return new EnvironmentalType();
    }

    /**
     * Create an instance of {@link BarFeederType }
     * 
     * @return
     *     the new instance of {@link BarFeederType }
     */
    public BarFeederType createBarFeederType() {
        return new BarFeederType();
    }

    /**
     * Create an instance of {@link InterfaceType }
     * 
     * @return
     *     the new instance of {@link InterfaceType }
     */
    public InterfaceType createInterfaceType() {
        return new InterfaceType();
    }

    /**
     * Create an instance of {@link InterfacesType }
     * 
     * @return
     *     the new instance of {@link InterfacesType }
     */
    public InterfacesType createInterfacesType() {
        return new InterfacesType();
    }

    /**
     * Create an instance of {@link LinearType }
     * 
     * @return
     *     the new instance of {@link LinearType }
     */
    public LinearType createLinearType() {
        return new LinearType();
    }

    /**
     * Create an instance of {@link PathType }
     * 
     * @return
     *     the new instance of {@link PathType }
     */
    public PathType createPathType() {
        return new PathType();
    }

    /**
     * Create an instance of {@link ControllerType }
     * 
     * @return
     *     the new instance of {@link ControllerType }
     */
    public ControllerType createControllerType() {
        return new ControllerType();
    }

    /**
     * Create an instance of {@link ResourcesType }
     * 
     * @return
     *     the new instance of {@link ResourcesType }
     */
    public ResourcesType createResourcesType() {
        return new ResourcesType();
    }

    /**
     * Create an instance of {@link PowerType }
     * 
     * @return
     *     the new instance of {@link PowerType }
     */
    public PowerType createPowerType() {
        return new PowerType();
    }

    /**
     * Create an instance of {@link MaterialsType }
     * 
     * @return
     *     the new instance of {@link MaterialsType }
     */
    public MaterialsType createMaterialsType() {
        return new MaterialsType();
    }

    /**
     * Create an instance of {@link StockType }
     * 
     * @return
     *     the new instance of {@link StockType }
     */
    public StockType createStockType() {
        return new StockType();
    }

    /**
     * Create an instance of {@link PersonnelType }
     * 
     * @return
     *     the new instance of {@link PersonnelType }
     */
    public PersonnelType createPersonnelType() {
        return new PersonnelType();
    }

    /**
     * Create an instance of {@link RotaryType }
     * 
     * @return
     *     the new instance of {@link RotaryType }
     */
    public RotaryType createRotaryType() {
        return new RotaryType();
    }

    /**
     * Create an instance of {@link SensorType }
     * 
     * @return
     *     the new instance of {@link SensorType }
     */
    public SensorType createSensorType() {
        return new SensorType();
    }

    /**
     * Create an instance of {@link ChuckType }
     * 
     * @return
     *     the new instance of {@link ChuckType }
     */
    public ChuckType createChuckType() {
        return new ChuckType();
    }

    /**
     * Create an instance of {@link DoorType }
     * 
     * @return
     *     the new instance of {@link DoorType }
     */
    public DoorType createDoorType() {
        return new DoorType();
    }

    /**
     * Create an instance of {@link HydraulicType }
     * 
     * @return
     *     the new instance of {@link HydraulicType }
     */
    public HydraulicType createHydraulicType() {
        return new HydraulicType();
    }

    /**
     * Create an instance of {@link PneumaticType }
     * 
     * @return
     *     the new instance of {@link PneumaticType }
     */
    public PneumaticType createPneumaticType() {
        return new PneumaticType();
    }

    /**
     * Create an instance of {@link CoolantType }
     * 
     * @return
     *     the new instance of {@link CoolantType }
     */
    public CoolantType createCoolantType() {
        return new CoolantType();
    }

    /**
     * Create an instance of {@link LubricationType }
     * 
     * @return
     *     the new instance of {@link LubricationType }
     */
    public LubricationType createLubricationType() {
        return new LubricationType();
    }

    /**
     * Create an instance of {@link EnclosureType }
     * 
     * @return
     *     the new instance of {@link EnclosureType }
     */
    public EnclosureType createEnclosureType() {
        return new EnclosureType();
    }

    /**
     * Create an instance of {@link ProtectiveType }
     * 
     * @return
     *     the new instance of {@link ProtectiveType }
     */
    public ProtectiveType createProtectiveType() {
        return new ProtectiveType();
    }

    /**
     * Create an instance of {@link ProcessPowerType }
     * 
     * @return
     *     the new instance of {@link ProcessPowerType }
     */
    public ProcessPowerType createProcessPowerType() {
        return new ProcessPowerType();
    }

    /**
     * Create an instance of {@link FeederType }
     * 
     * @return
     *     the new instance of {@link FeederType }
     */
    public FeederType createFeederType() {
        return new FeederType();
    }

    /**
     * Create an instance of {@link DielectricType }
     * 
     * @return
     *     the new instance of {@link DielectricType }
     */
    public DielectricType createDielectricType() {
        return new DielectricType();
    }

    /**
     * Create an instance of {@link DoorInterfaceType }
     * 
     * @return
     *     the new instance of {@link DoorInterfaceType }
     */
    public DoorInterfaceType createDoorInterfaceType() {
        return new DoorInterfaceType();
    }

    /**
     * Create an instance of {@link ChuckInterfaceType }
     * 
     * @return
     *     the new instance of {@link ChuckInterfaceType }
     */
    public ChuckInterfaceType createChuckInterfaceType() {
        return new ChuckInterfaceType();
    }

    /**
     * Create an instance of {@link BarFeederInterfaceType }
     * 
     * @return
     *     the new instance of {@link BarFeederInterfaceType }
     */
    public BarFeederInterfaceType createBarFeederInterfaceType() {
        return new BarFeederInterfaceType();
    }

    /**
     * Create an instance of {@link MaterialHandlerInterfaceType }
     * 
     * @return
     *     the new instance of {@link MaterialHandlerInterfaceType }
     */
    public MaterialHandlerInterfaceType createMaterialHandlerInterfaceType() {
        return new MaterialHandlerInterfaceType();
    }

    /**
     * Create an instance of {@link DepositionType }
     * 
     * @return
     *     the new instance of {@link DepositionType }
     */
    public DepositionType createDepositionType() {
        return new DepositionType();
    }

    /**
     * Create an instance of {@link EndEffectorType }
     * 
     * @return
     *     the new instance of {@link EndEffectorType }
     */
    public EndEffectorType createEndEffectorType() {
        return new EndEffectorType();
    }

    /**
     * Create an instance of {@link WorkEnvelopeType }
     * 
     * @return
     *     the new instance of {@link WorkEnvelopeType }
     */
    public WorkEnvelopeType createWorkEnvelopeType() {
        return new WorkEnvelopeType();
    }

    /**
     * Create an instance of {@link DataItemRefType }
     * 
     * @return
     *     the new instance of {@link DataItemRefType }
     */
    public DataItemRefType createDataItemRefType() {
        return new DataItemRefType();
    }

    /**
     * Create an instance of {@link ComponentRefType }
     * 
     * @return
     *     the new instance of {@link ComponentRefType }
     */
    public ComponentRefType createComponentRefType() {
        return new ComponentRefType();
    }

    /**
     * Create an instance of {@link SensorConfigurationType }
     * 
     * @return
     *     the new instance of {@link SensorConfigurationType }
     */
    public SensorConfigurationType createSensorConfigurationType() {
        return new SensorConfigurationType();
    }

    /**
     * Create an instance of {@link SpecificationsType }
     * 
     * @return
     *     the new instance of {@link SpecificationsType }
     */
    public SpecificationsType createSpecificationsType() {
        return new SpecificationsType();
    }

    /**
     * Create an instance of {@link SpecificationType }
     * 
     * @return
     *     the new instance of {@link SpecificationType }
     */
    public SpecificationType createSpecificationType() {
        return new SpecificationType();
    }

    /**
     * Create an instance of {@link ConstraintType }
     * 
     * @return
     *     the new instance of {@link ConstraintType }
     */
    public ConstraintType createConstraintType() {
        return new ConstraintType();
    }

    /**
     * Create an instance of {@link MaximumType }
     * 
     * @return
     *     the new instance of {@link MaximumType }
     */
    public MaximumType createMaximumType() {
        return new MaximumType();
    }

    /**
     * Create an instance of {@link MinimumType }
     * 
     * @return
     *     the new instance of {@link MinimumType }
     */
    public MinimumType createMinimumType() {
        return new MinimumType();
    }

    /**
     * Create an instance of {@link NominalType }
     * 
     * @return
     *     the new instance of {@link NominalType }
     */
    public NominalType createNominalType() {
        return new NominalType();
    }

    /**
     * Create an instance of {@link RelationshipsType }
     * 
     * @return
     *     the new instance of {@link RelationshipsType }
     */
    public RelationshipsType createRelationshipsType() {
        return new RelationshipsType();
    }

    /**
     * Create an instance of {@link ComponentRelationshipType }
     * 
     * @return
     *     the new instance of {@link ComponentRelationshipType }
     */
    public ComponentRelationshipType createComponentRelationshipType() {
        return new ComponentRelationshipType();
    }

    /**
     * Create an instance of {@link DeviceRelationshipType }
     * 
     * @return
     *     the new instance of {@link DeviceRelationshipType }
     */
    public DeviceRelationshipType createDeviceRelationshipType() {
        return new DeviceRelationshipType();
    }

    /**
     * Create an instance of {@link CoordinateSystemsType }
     * 
     * @return
     *     the new instance of {@link CoordinateSystemsType }
     */
    public CoordinateSystemsType createCoordinateSystemsType() {
        return new CoordinateSystemsType();
    }

    /**
     * Create an instance of {@link AssetCountsType }
     * 
     * @return
     *     the new instance of {@link AssetCountsType }
     */
    public AssetCountsType createAssetCountsType() {
        return new AssetCountsType();
    }

    /**
     * Create an instance of {@link AssetCountType }
     * 
     * @return
     *     the new instance of {@link AssetCountType }
     */
    public AssetCountType createAssetCountType() {
        return new AssetCountType();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     * @return
     *     the new instance of {@link HeaderType }
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link DevicesType }
     * 
     * @return
     *     the new instance of {@link DevicesType }
     */
    public DevicesType createDevicesType() {
        return new DevicesType();
    }

    /**
     * Create an instance of {@link ComponentDescriptionType }
     * 
     * @return
     *     the new instance of {@link ComponentDescriptionType }
     */
    public ComponentDescriptionType createComponentDescriptionType() {
        return new ComponentDescriptionType();
    }

    /**
     * Create an instance of {@link ComponentsType }
     * 
     * @return
     *     the new instance of {@link ComponentsType }
     */
    public ComponentsType createComponentsType() {
        return new ComponentsType();
    }

    /**
     * Create an instance of {@link CompositionsType }
     * 
     * @return
     *     the new instance of {@link CompositionsType }
     */
    public CompositionsType createCompositionsType() {
        return new CompositionsType();
    }

    /**
     * Create an instance of {@link CompositionType }
     * 
     * @return
     *     the new instance of {@link CompositionType }
     */
    public CompositionType createCompositionType() {
        return new CompositionType();
    }

    /**
     * Create an instance of {@link ReferencesType }
     * 
     * @return
     *     the new instance of {@link ReferencesType }
     */
    public ReferencesType createReferencesType() {
        return new ReferencesType();
    }

    /**
     * Create an instance of {@link ComponentConfigurationType }
     * 
     * @return
     *     the new instance of {@link ComponentConfigurationType }
     */
    public ComponentConfigurationType createComponentConfigurationType() {
        return new ComponentConfigurationType();
    }

    /**
     * Create an instance of {@link ChannelsType }
     * 
     * @return
     *     the new instance of {@link ChannelsType }
     */
    public ChannelsType createChannelsType() {
        return new ChannelsType();
    }

    /**
     * Create an instance of {@link ChannelType }
     * 
     * @return
     *     the new instance of {@link ChannelType }
     */
    public ChannelType createChannelType() {
        return new ChannelType();
    }

    /**
     * Create an instance of {@link CoordinateSystemType }
     * 
     * @return
     *     the new instance of {@link CoordinateSystemType }
     */
    public CoordinateSystemType createCoordinateSystemType() {
        return new CoordinateSystemType();
    }

    /**
     * Create an instance of {@link OriginType }
     * 
     * @return
     *     the new instance of {@link OriginType }
     */
    public OriginType createOriginType() {
        return new OriginType();
    }

    /**
     * Create an instance of {@link TransformationType }
     * 
     * @return
     *     the new instance of {@link TransformationType }
     */
    public TransformationType createTransformationType() {
        return new TransformationType();
    }

    /**
     * Create an instance of {@link DataItemDescriptionType }
     * 
     * @return
     *     the new instance of {@link DataItemDescriptionType }
     */
    public DataItemDescriptionType createDataItemDescriptionType() {
        return new DataItemDescriptionType();
    }

    /**
     * Create an instance of {@link DataItemsType }
     * 
     * @return
     *     the new instance of {@link DataItemsType }
     */
    public DataItemsType createDataItemsType() {
        return new DataItemsType();
    }

    /**
     * Create an instance of {@link DataItemType }
     * 
     * @return
     *     the new instance of {@link DataItemType }
     */
    public DataItemType createDataItemType() {
        return new DataItemType();
    }

    /**
     * Create an instance of {@link DataItemConstraintsType }
     * 
     * @return
     *     the new instance of {@link DataItemConstraintsType }
     */
    public DataItemConstraintsType createDataItemConstraintsType() {
        return new DataItemConstraintsType();
    }

    /**
     * Create an instance of {@link FiltersType }
     * 
     * @return
     *     the new instance of {@link FiltersType }
     */
    public FiltersType createFiltersType() {
        return new FiltersType();
    }

    /**
     * Create an instance of {@link DataItemBaseType }
     * 
     * @return
     *     the new instance of {@link DataItemBaseType }
     */
    public DataItemBaseType createDataItemBaseType() {
        return new DataItemBaseType();
    }

    /**
     * Create an instance of {@link DataItemValueElementType }
     * 
     * @return
     *     the new instance of {@link DataItemValueElementType }
     */
    public DataItemValueElementType createDataItemValueElementType() {
        return new DataItemValueElementType();
    }

    /**
     * Create an instance of {@link DataItemFilterType }
     * 
     * @return
     *     the new instance of {@link DataItemFilterType }
     */
    public DataItemFilterType createDataItemFilterType() {
        return new DataItemFilterType();
    }

    /**
     * Create an instance of {@link DataItemSourceType }
     * 
     * @return
     *     the new instance of {@link DataItemSourceType }
     */
    public DataItemSourceType createDataItemSourceType() {
        return new DataItemSourceType();
    }

    /**
     * Create an instance of {@link DataItemDefinitionType }
     * 
     * @return
     *     the new instance of {@link DataItemDefinitionType }
     */
    public DataItemDefinitionType createDataItemDefinitionType() {
        return new DataItemDefinitionType();
    }

    /**
     * Create an instance of {@link EntryDefinitionsType }
     * 
     * @return
     *     the new instance of {@link EntryDefinitionsType }
     */
    public EntryDefinitionsType createEntryDefinitionsType() {
        return new EntryDefinitionsType();
    }

    /**
     * Create an instance of {@link EntryDefinitionType }
     * 
     * @return
     *     the new instance of {@link EntryDefinitionType }
     */
    public EntryDefinitionType createEntryDefinitionType() {
        return new EntryDefinitionType();
    }

    /**
     * Create an instance of {@link CellDefinitionsType }
     * 
     * @return
     *     the new instance of {@link CellDefinitionsType }
     */
    public CellDefinitionsType createCellDefinitionsType() {
        return new CellDefinitionsType();
    }

    /**
     * Create an instance of {@link CellDefinitionType }
     * 
     * @return
     *     the new instance of {@link CellDefinitionType }
     */
    public CellDefinitionType createCellDefinitionType() {
        return new CellDefinitionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MTConnectDevicesType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MTConnectDevicesType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "MTConnectDevices")
    public JAXBElement<MTConnectDevicesType> createMTConnectDevices(MTConnectDevicesType value) {
        return new JAXBElement<>(_MTConnectDevices_QNAME, MTConnectDevicesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComponentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ComponentType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Component")
    public JAXBElement<ComponentType> createComponent(ComponentType value) {
        return new JAXBElement<>(_Component_QNAME, ComponentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommonComponentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CommonComponentType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "CommonComponent", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Component")
    public JAXBElement<CommonComponentType> createCommonComponent(CommonComponentType value) {
        return new JAXBElement<>(_CommonComponent_QNAME, CommonComponentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeviceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DeviceType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Device", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Component")
    public JAXBElement<DeviceType> createDevice(DeviceType value) {
        return new JAXBElement<>(_Device_QNAME, DeviceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActuatorType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ActuatorType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Actuator", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "CommonComponent")
    public JAXBElement<ActuatorType> createActuator(ActuatorType value) {
        return new JAXBElement<>(_Actuator_QNAME, ActuatorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuxiliariesType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AuxiliariesType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Auxiliaries", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "CommonComponent")
    public JAXBElement<AuxiliariesType> createAuxiliaries(AuxiliariesType value) {
        return new JAXBElement<>(_Auxiliaries_QNAME, AuxiliariesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AxesType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AxesType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Axes", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "CommonComponent")
    public JAXBElement<AxesType> createAxes(AxesType value) {
        return new JAXBElement<>(_Axes_QNAME, AxesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElectricType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ElectricType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Electric", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Systems")
    public JAXBElement<ElectricType> createElectric(ElectricType value) {
        return new JAXBElement<>(_Electric_QNAME, ElectricType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SystemsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SystemsType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Systems", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "CommonComponent")
    public JAXBElement<SystemsType> createSystems(SystemsType value) {
        return new JAXBElement<>(_Systems_QNAME, SystemsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoaderType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LoaderType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Loader", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Auxiliaries")
    public JAXBElement<LoaderType> createLoader(LoaderType value) {
        return new JAXBElement<>(_Loader_QNAME, LoaderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WasteDisposalType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link WasteDisposalType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "WasteDisposal", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Auxiliaries")
    public JAXBElement<WasteDisposalType> createWasteDisposal(WasteDisposalType value) {
        return new JAXBElement<>(_WasteDisposal_QNAME, WasteDisposalType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ToolingDeliveryType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ToolingDeliveryType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "ToolingDelivery", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Auxiliaries")
    public JAXBElement<ToolingDeliveryType> createToolingDelivery(ToolingDeliveryType value) {
        return new JAXBElement<>(_ToolingDelivery_QNAME, ToolingDeliveryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnvironmentalType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EnvironmentalType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Environmental", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Auxiliaries")
    public JAXBElement<EnvironmentalType> createEnvironmental(EnvironmentalType value) {
        return new JAXBElement<>(_Environmental_QNAME, EnvironmentalType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BarFeederType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BarFeederType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "BarFeeder", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Auxiliaries")
    public JAXBElement<BarFeederType> createBarFeeder(BarFeederType value) {
        return new JAXBElement<>(_BarFeeder_QNAME, BarFeederType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InterfaceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InterfaceType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Interface", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "CommonComponent")
    public JAXBElement<InterfaceType> createInterface(InterfaceType value) {
        return new JAXBElement<>(_Interface_QNAME, InterfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InterfacesType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InterfacesType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Interfaces", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "CommonComponent")
    public JAXBElement<InterfacesType> createInterfaces(InterfacesType value) {
        return new JAXBElement<>(_Interfaces_QNAME, InterfacesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinearType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LinearType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Linear", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Axes")
    public JAXBElement<LinearType> createLinear(LinearType value) {
        return new JAXBElement<>(_Linear_QNAME, LinearType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PathType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PathType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Path", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Controller")
    public JAXBElement<PathType> createPath(PathType value) {
        return new JAXBElement<>(_Path_QNAME, PathType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ControllerType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ControllerType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Controller", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "CommonComponent")
    public JAXBElement<ControllerType> createController(ControllerType value) {
        return new JAXBElement<>(_Controller_QNAME, ControllerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourcesType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ResourcesType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Resources", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "CommonComponent")
    public JAXBElement<ResourcesType> createResources(ResourcesType value) {
        return new JAXBElement<>(_Resources_QNAME, ResourcesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PowerType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PowerType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Power", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "CommonComponent")
    public JAXBElement<PowerType> createPower(PowerType value) {
        return new JAXBElement<>(_Power_QNAME, PowerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MaterialsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MaterialsType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Materials", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Resources")
    public JAXBElement<MaterialsType> createMaterials(MaterialsType value) {
        return new JAXBElement<>(_Materials_QNAME, MaterialsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StockType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StockType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Stock", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Materials")
    public JAXBElement<StockType> createStock(StockType value) {
        return new JAXBElement<>(_Stock_QNAME, StockType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonnelType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PersonnelType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Personnel", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Resources")
    public JAXBElement<PersonnelType> createPersonnel(PersonnelType value) {
        return new JAXBElement<>(_Personnel_QNAME, PersonnelType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RotaryType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RotaryType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Rotary", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Axes")
    public JAXBElement<RotaryType> createRotary(RotaryType value) {
        return new JAXBElement<>(_Rotary_QNAME, RotaryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SensorType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SensorType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Sensor", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Auxiliaries")
    public JAXBElement<SensorType> createSensor(SensorType value) {
        return new JAXBElement<>(_Sensor_QNAME, SensorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChuckType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ChuckType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Chuck", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Rotary")
    public JAXBElement<ChuckType> createChuck(ChuckType value) {
        return new JAXBElement<>(_Chuck_QNAME, ChuckType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DoorType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DoorType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Door", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "CommonComponent")
    public JAXBElement<DoorType> createDoor(DoorType value) {
        return new JAXBElement<>(_Door_QNAME, DoorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HydraulicType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link HydraulicType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Hydraulic", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Systems")
    public JAXBElement<HydraulicType> createHydraulic(HydraulicType value) {
        return new JAXBElement<>(_Hydraulic_QNAME, HydraulicType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PneumaticType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PneumaticType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Pneumatic", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Systems")
    public JAXBElement<PneumaticType> createPneumatic(PneumaticType value) {
        return new JAXBElement<>(_Pneumatic_QNAME, PneumaticType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoolantType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CoolantType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Coolant", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Systems")
    public JAXBElement<CoolantType> createCoolant(CoolantType value) {
        return new JAXBElement<>(_Coolant_QNAME, CoolantType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LubricationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LubricationType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Lubrication", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Systems")
    public JAXBElement<LubricationType> createLubrication(LubricationType value) {
        return new JAXBElement<>(_Lubrication_QNAME, LubricationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnclosureType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EnclosureType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Enclosure", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Systems")
    public JAXBElement<EnclosureType> createEnclosure(EnclosureType value) {
        return new JAXBElement<>(_Enclosure_QNAME, EnclosureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProtectiveType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ProtectiveType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Protective", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Systems")
    public JAXBElement<ProtectiveType> createProtective(ProtectiveType value) {
        return new JAXBElement<>(_Protective_QNAME, ProtectiveType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessPowerType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ProcessPowerType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "ProcessPower", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Systems")
    public JAXBElement<ProcessPowerType> createProcessPower(ProcessPowerType value) {
        return new JAXBElement<>(_ProcessPower_QNAME, ProcessPowerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FeederType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FeederType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Feeder", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Systems")
    public JAXBElement<FeederType> createFeeder(FeederType value) {
        return new JAXBElement<>(_Feeder_QNAME, FeederType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DielectricType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DielectricType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Dielectric", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Systems")
    public JAXBElement<DielectricType> createDielectric(DielectricType value) {
        return new JAXBElement<>(_Dielectric_QNAME, DielectricType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DoorInterfaceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DoorInterfaceType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "DoorInterface", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "CommonComponent")
    public JAXBElement<DoorInterfaceType> createDoorInterface(DoorInterfaceType value) {
        return new JAXBElement<>(_DoorInterface_QNAME, DoorInterfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChuckInterfaceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ChuckInterfaceType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "ChuckInterface", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "CommonComponent")
    public JAXBElement<ChuckInterfaceType> createChuckInterface(ChuckInterfaceType value) {
        return new JAXBElement<>(_ChuckInterface_QNAME, ChuckInterfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BarFeederInterfaceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BarFeederInterfaceType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "BarFeederInterface", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "CommonComponent")
    public JAXBElement<BarFeederInterfaceType> createBarFeederInterface(BarFeederInterfaceType value) {
        return new JAXBElement<>(_BarFeederInterface_QNAME, BarFeederInterfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MaterialHandlerInterfaceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MaterialHandlerInterfaceType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "MaterialHandlerInterface", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "CommonComponent")
    public JAXBElement<MaterialHandlerInterfaceType> createMaterialHandlerInterface(MaterialHandlerInterfaceType value) {
        return new JAXBElement<>(_MaterialHandlerInterface_QNAME, MaterialHandlerInterfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DepositionType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DepositionType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Deposition", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "CommonComponent")
    public JAXBElement<DepositionType> createDeposition(DepositionType value) {
        return new JAXBElement<>(_Deposition_QNAME, DepositionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndEffectorType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EndEffectorType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "EndEffector", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "CommonComponent")
    public JAXBElement<EndEffectorType> createEndEffector(EndEffectorType value) {
        return new JAXBElement<>(_EndEffector_QNAME, EndEffectorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkEnvelopeType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link WorkEnvelopeType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "WorkEnvelope", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "CommonComponent")
    public JAXBElement<WorkEnvelopeType> createWorkEnvelope(WorkEnvelopeType value) {
        return new JAXBElement<>(_WorkEnvelope_QNAME, WorkEnvelopeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Reference")
    public JAXBElement<ReferenceType> createReference(ReferenceType value) {
        return new JAXBElement<>(_Reference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataItemRefType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DataItemRefType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "DataItemRef", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Reference")
    public JAXBElement<DataItemRefType> createDataItemRef(DataItemRefType value) {
        return new JAXBElement<>(_DataItemRef_QNAME, DataItemRefType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComponentRefType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ComponentRefType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "ComponentRef", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Reference")
    public JAXBElement<ComponentRefType> createComponentRef(ComponentRefType value) {
        return new JAXBElement<>(_ComponentRef_QNAME, ComponentRefType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractConfigurationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractConfigurationType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "AbstractConfiguration")
    public JAXBElement<AbstractConfigurationType> createAbstractConfiguration(AbstractConfigurationType value) {
        return new JAXBElement<>(_AbstractConfiguration_QNAME, AbstractConfigurationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SensorConfigurationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SensorConfigurationType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "SensorConfiguration", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "AbstractConfiguration")
    public JAXBElement<SensorConfigurationType> createSensorConfiguration(SensorConfigurationType value) {
        return new JAXBElement<>(_SensorConfiguration_QNAME, SensorConfigurationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecificationsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SpecificationsType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Specifications", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "AbstractConfiguration")
    public JAXBElement<SpecificationsType> createSpecifications(SpecificationsType value) {
        return new JAXBElement<>(_Specifications_QNAME, SpecificationsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractSpecificationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractSpecificationType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "AbstractSpecification")
    public JAXBElement<AbstractSpecificationType> createAbstractSpecification(AbstractSpecificationType value) {
        return new JAXBElement<>(_AbstractSpecification_QNAME, AbstractSpecificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecificationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SpecificationType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Specification", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "AbstractSpecification")
    public JAXBElement<SpecificationType> createSpecification(SpecificationType value) {
        return new JAXBElement<>(_Specification_QNAME, SpecificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecificationValueType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SpecificationValueType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "SpecificationValue")
    public JAXBElement<SpecificationValueType> createSpecificationValue(SpecificationValueType value) {
        return new JAXBElement<>(_SpecificationValue_QNAME, SpecificationValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConstraintType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ConstraintType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Constraint", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "SpecificationValue")
    public JAXBElement<ConstraintType> createConstraint(ConstraintType value) {
        return new JAXBElement<>(_Constraint_QNAME, ConstraintType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MaximumType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MaximumType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Maximum", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Constraint")
    public JAXBElement<MaximumType> createMaximum(MaximumType value) {
        return new JAXBElement<>(_Maximum_QNAME, MaximumType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MinimumType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MinimumType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Minimum", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Constraint")
    public JAXBElement<MinimumType> createMinimum(MinimumType value) {
        return new JAXBElement<>(_Minimum_QNAME, MinimumType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NominalType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NominalType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Nominal", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Constraint")
    public JAXBElement<NominalType> createNominal(NominalType value) {
        return new JAXBElement<>(_Nominal_QNAME, NominalType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationshipsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RelationshipsType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Relationships", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "AbstractConfiguration")
    public JAXBElement<RelationshipsType> createRelationships(RelationshipsType value) {
        return new JAXBElement<>(_Relationships_QNAME, RelationshipsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationshipType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RelationshipType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "Relationship")
    public JAXBElement<RelationshipType> createRelationship(RelationshipType value) {
        return new JAXBElement<>(_Relationship_QNAME, RelationshipType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComponentRelationshipType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ComponentRelationshipType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "ComponentRelationship", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Relationship")
    public JAXBElement<ComponentRelationshipType> createComponentRelationship(ComponentRelationshipType value) {
        return new JAXBElement<>(_ComponentRelationship_QNAME, ComponentRelationshipType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeviceRelationshipType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DeviceRelationshipType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "DeviceRelationship", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "Relationship")
    public JAXBElement<DeviceRelationshipType> createDeviceRelationship(DeviceRelationshipType value) {
        return new JAXBElement<>(_DeviceRelationship_QNAME, DeviceRelationshipType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoordinateSystemsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CoordinateSystemsType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "CoordinateSystems", substitutionHeadNamespace = "urn:mtconnect.org:MTConnectDevices:1.6", substitutionHeadName = "AbstractConfiguration")
    public JAXBElement<CoordinateSystemsType> createCoordinateSystems(CoordinateSystemsType value) {
        return new JAXBElement<>(_CoordinateSystems_QNAME, CoordinateSystemsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoordinateSystemType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CoordinateSystemType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectDevices:1.6", name = "CoordinateSystem", scope = CoordinateSystemsType.class)
    public JAXBElement<CoordinateSystemType> createCoordinateSystemsTypeCoordinateSystem(CoordinateSystemType value) {
        return new JAXBElement<>(_CoordinateSystemsTypeCoordinateSystem_QNAME, CoordinateSystemType.class, CoordinateSystemsType.class, value);
    }

}
