//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.hivemq.edge.adapters.mtconnect.schemas.devices.devices_1_6;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * An XML container used to organize information for lower level elements
 *         representing types of items, materials, and personnel that support the
 *         operation of a piece of equipment or work to be performed at a location.
 *         resources also represents materials or other items consumed or
 *         transformed by a piece of equipment for production of parts or other
 *         types of goods.
 * 
 * <p>Java class for ResourcesType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ResourcesType">
 *   <complexContent>
 *     <extension base="{urn:mtconnect.org:MTConnectDevices:1.6}CommonComponentType">
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@com.fasterxml.jackson.annotation.JsonTypeName(value = "ResourcesType")
@XmlType(name = "ResourcesType")
@XmlSeeAlso({
    MaterialsType.class,
    PersonnelType.class
})
public class ResourcesType
    extends CommonComponentType
{


}
