//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.hivemq.edge.adapters.mtconnect.schemas.devices.devices_1_6;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * An XML container used to organize information for lower level elements
 *         representing the major sub-systems that are permanently integrated into
 *         a piece of equipment.
 * 
 * <p>Java class for SystemsType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="SystemsType">
 *   <complexContent>
 *     <extension base="{urn:mtconnect.org:MTConnectDevices:1.6}CommonComponentType">
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@com.fasterxml.jackson.annotation.JsonTypeName(value = "SystemsType")
@XmlType(name = "SystemsType")
@XmlSeeAlso({
    ElectricType.class,
    HydraulicType.class,
    PneumaticType.class,
    CoolantType.class,
    LubricationType.class,
    EnclosureType.class,
    ProtectiveType.class,
    ProcessPowerType.class,
    FeederType.class,
    DielectricType.class
})
public class SystemsType
    extends CommonComponentType
{


}
