package com.hivemq.testordering

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

/**
 * Report how well the last test run filled its parallel forks, and whether a fresh ordering would help.
 *
 * Two halves:
 *
 *  - **What actually happened.** From the per-JVM fork logs: how many forks were busy at each decile of the
 *    run, the average concurrency, and how much of the wall clock was spent below full occupancy. This is
 *    measured, not modelled.
 *  - **What a different ordering would give.** A simulation, for a range of fork counts, of the snake
 *    arrangement under the COMMITTED ordering versus the ordering THIS RUN implies.
 *
 * The gap between those two simulated columns is the decision: if this run's ordering is meaningfully
 * better, copy the generated file over the committed one and raise a PR. If not, leave it alone.
 *
 * TWO THINGS THE SIMULATION DELIBERATELY DOES NOT DO.
 *
 * The committed file's SECONDS are never added up. They only decide the sort order. Both simulations take
 * every duration from this run, so the ordering is the only variable between them -- which is what makes the
 * two numbers comparable at all. (The seconds stay in the committed file because they are useful to read.)
 *
 * Both simulations cover exactly the same set of classes: everything this run measured. A class the run
 * measured but the committed file has never heard of is unranked, so it sorts last in the committed
 * ordering -- but its time still counts. Dropping it would let the committed ordering quietly benefit from
 * ignoring real work, and the comparison would be rigged.
 */
abstract class ReportTestConcurrencyTask : DefaultTask() {
    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val resultsDir: DirectoryProperty

    /**
     * Per-JVM logs from ForkAttributionListener. Not an @InputDirectory: the suite that has no listener
     * never creates it, and a missing @InputDirectory fails the task rather than skipping the section.
     */
    @get:Internal
    abstract val forkLogsDir: DirectoryProperty

    @get:Optional
    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val committedTimings: RegularFileProperty

    @get:OutputFile
    abstract val runTimings: RegularFileProperty

    @get:Input
    abstract val forkCounts: ListProperty<Int>

    @get:Input
    @get:Optional
    abstract val actualForks: Property<Int>

    init {
        group = "verification"
        description = "Report how well the last test run filled its forks, and whether a fresh ordering would help"
        outputs.upToDateWhen { false }
    }

    @TaskAction
    fun run() {
        val results = readRunResults(resultsDir.get().asFile)
        if (results.isEmpty()) {
            throw GradleException(
                "No JUnit XML found in ${resultsDir.get().asFile}. Run the test suite first -- " +
                    "this reports on a run that has happened."
            )
        }

        val failed = results.filterValues { it.failures > 0 }
        if (failed.isNotEmpty()) {
            logger.warn("")
            logger.warn("WARNING: ${failed.size} class(es) failed in this run.")
            logger.warn("A failing class stops early, so its measured time understates the real one.")
            logger.warn("Treat the numbers below as provisional until the suite is green.")
        }

        // R -- this run. The durations here are the ONLY durations used anywhere below.
        val runtimes = results.mapValues { it.value.seconds }
        val committedFile = committedTimings.orNull?.asFile
        val committed = committedFile?.let { readTimings(it) } ?: emptyMap()

        writeTimings(
            runTimings.get().asFile,
            runtimes,
            // ONE header, because adopting a new ordering is a plain `cp` of this file over the committed
            // one. So it has to read as the committed file -- that is where someone will find it and wonder.
            // Short by design: the explanation lives in the Edge Lore, not in a data file.
            listOf(
                "This file is used to guide the distribution of test classes to",
                "concurrent JVMs (forks) to minimize total wall clock time.",
                "DO NOT EDIT THIS FILE MANUALLY.",
                "",
                "Versions of this file exist in two different places:",
                "  gradle/  the committed ordering, used by every local test run",
                "  build/   what the last run measured, regenerated by the report below",
                "",
                "After a successful test run use the following command to get a report:",
                "  ./gradlew :hivemq-edge:reportTestConcurrency   (core unit tests)",
                "  ./gradlew reportTestConcurrency                (integration tests)",
                "",
                "If it shows a real gain, adopt this ordering and raise a PR:",
                "  cp build/test-class-timings.csv gradle/test-class-timings.csv",
                "",
                "https://hivemq.github.io/hivemq-edge-lore/3-Quality-and-Testing/balancing-the-parallel-forks/"
            )
        )

        reportOccupancy()
        reportSimulation(runtimes, committed, committedFile)
    }

    /**
     * What the run actually did, from the fork logs.
     *
     * Each line is `endEpochMs offsetFromJvmStart durationMs sequence className`, so a class occupied its
     * JVM over [end - duration, end]. Overlapping those intervals gives the number of forks busy at any
     * moment.
     *
     * The window is FIRST CLASS START to LAST CLASS END -- test execution only. Everything before the first
     * class (compilation, Gradle configuration, JVM startup) is not something the ordering can influence,
     * and including it drags the concurrency down by a factor that has nothing to do with the balance.
     *
     * Concurrency is AVERAGED OVER EACH DECILE, not sampled at an instant. Sampling lands between classes
     * often enough to print 0 in the middle of a fully busy run, which reads as a stall that never happened.
     */
    private fun reportOccupancy() {
        val dir = forkLogsDir.orNull?.asFile
        val files = dir?.listFiles { f -> f.isFile && f.name.endsWith(".log") }?.toList().orEmpty()
        if (files.isEmpty()) {
            logger.lifecycle("")
            logger.lifecycle("Fork occupancy: no fork logs (the run predates them, or -PnoForkLogs was set)")
            return
        }

        // (start, end) in epoch millis for every class, grouped by the run its JVM belonged to. The
        // directory ACCUMULATES -- Gradle never clears it -- so logs from earlier runs sit beside this
        // one's. The build stamps each fork with a run id precisely so they can be told apart; timing
        // cannot do it, because the idle gap while the build recompiles between two runs is the same
        // length as a slow test class.
        val byRun = mutableMapOf<String, MutableList<Pair<Long, Long>>>()
        files.forEach { file ->
            var runId = "unknown"
            file.forEachLine { line ->
                if (line.startsWith("#")) {
                    RUN_ID.find(line)?.let { runId = it.groupValues[1] }
                    return@forEachLine
                }
                val f = line.split(' ')
                if (f.size < 5) return@forEachLine
                val end = f[0].toLongOrNull() ?: return@forEachLine
                val duration = f[2].toLongOrNull() ?: return@forEachLine
                byRun.getOrPut(runId) { mutableListOf() } += (end - duration) to end
            }
        }
        if (byRun.isEmpty()) {
            logger.lifecycle("")
            logger.lifecycle("Fork occupancy: fork logs present but empty")
            return
        }

        // The most recent run is the one that ended last.
        val latest = byRun.maxBy { it.value.maxOf { span -> span.second } }
        val spans = latest.value
        val ignored = byRun.values.sumOf { it.size } - spans.size
        val otherRuns = byRun.size - 1

        val start = spans.minOf { it.first }
        val finish = spans.maxOf { it.second }
        val window = (finish - start).coerceAtLeast(1)
        val work = spans.sumOf { it.second - it.first }

        logger.lifecycle("")
        logger.lifecycle("Fork occupancy over the test execution -- ${spans.size} classes in ${fmt(window)}")
        if (ignored > 0) {
            logger.lifecycle("  ($ignored class record(s) from $otherRuns earlier run(s) in the same directory ignored)")
        }
        logger.lifecycle("")
        logger.lifecycle("  % of execution   forks busy")
        for (i in 0 until 10) {
            val lo = start + window * i / 10
            val hi = start + window * (i + 1) / 10
            val occupied = spans.sumOf { (a, b) -> (minOf(b, hi) - maxOf(a, lo)).coerceAtLeast(0) }
            logger.lifecycle(String.format("  %6d-%3d%%       %.1f", i * 10, (i + 1) * 10, occupied.toDouble() / (hi - lo)))
        }
        logger.lifecycle("")
        logger.lifecycle(
            String.format(
                "  average concurrency %.1f  (%s of work in %s of execution)",
                work.toDouble() / window, fmt(work), fmt(window)
            )
        )
    }

    private fun reportSimulation(
        runtimes: Map<String, Double>,
        committed: Map<String, Double>,
        committedFile: java.io.File?
    ) {
        val classes = runtimes.keys.toList()
        val onlyInRun = classes.filter { it !in committed }
        val onlyInCommitted = committed.keys.filter { it !in runtimes }

        logger.lifecycle("")
        logger.lifecycle("What a different ordering would give")
        if (committedFile == null || committed.isEmpty()) {
            logger.lifecycle("  No committed timings yet, so there is nothing to compare against.")
        } else {
            logger.lifecycle(
                "  Committed file: ${committed.size} entries -- " +
                    "${onlyInRun.size} class(es) it does not rank (they sort last), " +
                    "${onlyInCommitted.size} it lists that did not run (ignored)"
            )
        }
        logger.lifecycle("")

        val forks = forkCounts.get().sorted().distinct()
        logger.lifecycle(
            if (committed.isEmpty()) {
                String.format("  %6s  %12s", "forks", "this run")
            } else {
                String.format("  %6s  %12s  %12s  %10s", "forks", "committed", "this run", "gain")
            }
        )

        forks.forEach { n ->
            val fromRun = simulate(arrange(classes, runtimes, n), runtimes, n)
            if (committed.isEmpty()) {
                logger.lifecycle(String.format("  %6d  %11.0fs", n, fromRun))
            } else {
                val fromCommitted = simulate(arrange(classes, committed, n), runtimes, n)
                val marker = if (actualForks.orNull == n) "  <- this machine" else ""
                logger.lifecycle(
                    String.format(
                        "  %6d  %11.0fs  %11.0fs  %9.0fs%s",
                        n, fromCommitted, fromRun, fromCommitted - fromRun, marker
                    )
                )
            }
        }

        logger.lifecycle("")
        logger.lifecycle("'gain' is what re-ordering would save. Adopt this run's ordering with:")
        logger.lifecycle("  cp ${runTimings.get().asFile} ${committedFile ?: "<committed file>"}")
        logger.lifecycle("then raise a PR -- the diff is a reordered CSV.")
        logger.lifecycle("")
    }

    private companion object {
        /** `# runId=... jvmStart=...` -- the header the build stamps onto every fork log. */
        val RUN_ID = Regex("runId=(\\S+)")
    }

    private fun fmt(millis: Long): String {
        val seconds = millis / 1000
        return if (seconds < 60) "${seconds}s" else "${seconds / 60}m${"%02d".format(seconds % 60)}s"
    }
}
