//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.hivemq.edge.adapters.mtconnect.schemas.devices.devices_2_0;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * The limit of a constraint
 * 
 * <p>Java class for ConstraintType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ConstraintType">
 *   <simpleContent>
 *     <extension base="<urn:mtconnect.org:MTConnectDevices:2.0>LimitValueType">
 *     </extension>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@com.fasterxml.jackson.annotation.JsonTypeName(value = "ConstraintType")
@XmlType(name = "ConstraintType", propOrder = {
    "value"
})
@XmlSeeAlso({
    MaximumType.class,
    MinimumType.class,
    NominalType.class,
    UpperLimitType.class,
    UpperWarningType.class,
    LowerWarningType.class,
    LowerLimitType.class
})
public abstract class ConstraintType {

    /**
     * The limit of a value
     * 
     */
    @XmlValue
    protected float value;

    /**
     * The limit of a value
     * 
     */
    public float getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(float value) {
        this.value = value;
    }

}
