openapi: 3.0.1
info:
  title: HiveMQ Edge REST API
  version: "2025.3-SNAPSHOT"
  description: |
    Note: This should be restructured and divided in individual files, to match the requirements of the 30019 ticket (splitting openAPI)
tags:
  - description: Data combining mappings, using the Combiner / Orchestrator paradigm
    name: Combiners
paths:
  /api/v1/management/combiners:
    get:
      description: Get all combiners
      summary: Get all combiners
      operationId: get-combiners
      tags:
        - Combiners
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CombinerList'
          description: Success
    post:
      description: Add a new combiner.
      summary: Add a new combiner
      operationId: add-combiner
      tags:
        - Combiners
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Combiner'
        description: The combiner to add
        required: true
      responses:
        "200":
          description: Success
        "409":
          content:
            application/json:
              schema:
                $ref: '../hivemq-edge-openapi-2025.3-SNAPSHOT.yaml#/components/schemas/ProblemDetails'
          description: Combiner already exists
  /api/v1/management/combiners/{combinerId}:
    get:
      description: Get a combiner by its unique Id.
      summary: Get a combiner
      operationId: getCombinersById
      tags:
        - Combiners
      parameters:
        - name: combinerId
          description: The unique id of the combiner to retrieve.
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Combiner'
          description: Success
        "404":
          content:
            application/json:
              schema:
                $ref: '../hivemq-edge-openapi-2025.3-SNAPSHOT.yaml#/components/schemas/ProblemDetails'
          description: Combiner not found
    delete:
      description: Delete the specified combiner.
      summary: Delete a combiner
      operationId: delete-combiner
      tags:
        - Combiners
      parameters:
        - name: combinerId
          description: The unique id of the combiner to delete.
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success
        "404":
          content:
            application/json:
              schema:
                $ref: '../hivemq-edge-openapi-2025.3-SNAPSHOT.yaml#/components/schemas/ProblemDetails'
          description: Combiner not found
    put:
      description: Update a combiner.
      summary: Update a combiner
      operationId: update-combiner
      tags:
        - Combiners
      parameters:
        - name: combinerId
          description: The unique id of the combiner to update.
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Combiner'
        description: The new content of the combiner
        required: true
      responses:
        "200":
          description: Success
        "409":
          content:
            application/json:
              schema:
                $ref: '../hivemq-edge-openapi-2025.3-SNAPSHOT.yaml#/components/schemas/ProblemDetails'
          description: Combiner already exists

components:
  schemas:
    CombinerList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Combiner'
    Combiner:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        sources:
          $ref: '#/components/schemas/EntityReferenceList'
        mappings:
          $ref: '#/components/schemas/DataCombiningList'
      required:
        - id
        - name
    DataCombiningList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/DataCombining'
    DataCombining:
      type: object
      description: Define individual rules for data combining, based on the entities selected in the Orchestrator
      properties:
        sources:
          type: object
          properties:
            tags:
              type: array
              items:
                type: string
                format: uuid
            topicFilters:
              type: array
              items:
                type: string
                format: uuid
        destination:
          type: string
          format: mqtt-topic
        instructions:
          type: array
          description: List of instructions to be applied to incoming data
          items:
            $ref: '../hivemq-edge-openapi-2025.3-SNAPSHOT.yaml#/components/schemas/Instruction'
      required:
        - instructions
    EntityReferenceList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/EntityReference'
    EntityType:
      type: string
      description: These are the prime entities owning tags and topic filters
      enum: [ADAPTER, DEVICE, BRIDGE, EDGE_BROKER]
    EntityReference:
      type: object
      description: We need this because we don't have a mechanism to identify a prime entity from an id
      properties:
        type:
          $ref: '#/components/schemas/EntityType'
        id:
          type: string
          format: uuid
        isPrimary:
          description: The source is the primary orchestrator of the composer
          type: boolean
          default: false
      required:
        - id
        - type

