//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.hivemq.edge.adapters.mtconnect.schemas.assets.assets_1_7;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The Pot or Spindle the cutting tool currently resides in.
 * 
 * <p>Java class for LocationType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="LocationType">
 *   <simpleContent>
 *     <extension base="<urn:mtconnect.org:MTConnectAssets:1.7>LocationValueType">
 *       <attribute name="type" use="required" type="{urn:mtconnect.org:MTConnectAssets:1.7}LocationsTypeType" />
 *       <attribute name="negativeOverlap" type="{urn:mtconnect.org:MTConnectAssets:1.7}OverlapType" />
 *       <attribute name="positiveOverlap" type="{urn:mtconnect.org:MTConnectAssets:1.7}OverlapType" />
 *       <attribute name="turret" type="{urn:mtconnect.org:MTConnectAssets:1.7}LocationRelationType" />
 *       <attribute name="toolMagazine" type="{urn:mtconnect.org:MTConnectAssets:1.7}LocationRelationType" />
 *       <attribute name="toolRack" type="{urn:mtconnect.org:MTConnectAssets:1.7}LocationRelationType" />
 *       <attribute name="toolBar" type="{urn:mtconnect.org:MTConnectAssets:1.7}LocationRelationType" />
 *       <attribute name="automaticToolChanger" type="{urn:mtconnect.org:MTConnectAssets:1.7}LocationRelationType" />
 *     </extension>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@com.fasterxml.jackson.annotation.JsonTypeName(value = "LocationType")
@XmlType(name = "LocationType", propOrder = {
    "value"
})
public class LocationType {

    /**
     * The tool location
     * 
     */
    @XmlValue
    protected BigInteger value;
    /**
     * The type of location
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "type")
    @XmlAttribute(name = "type", required = true)
    protected LocationsTypeType type;
    /**
     * The number of location at lower index values from this location.
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "negativeOverlap")
    @XmlAttribute(name = "negativeOverlap")
    protected BigInteger negativeOverlap;
    /**
     * The number of locations at higher index value from this location.
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "positiveOverlap")
    @XmlAttribute(name = "positiveOverlap")
    protected BigInteger positiveOverlap;
    /**
     * A tool mounting mechanism that holds any number of tools. Tools
     *               are located in {{block(Station)}}s . Tools are positioned for use
     *               in the manufacturing process by rotating the {{block(Turret)}}.
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "turret")
    @XmlAttribute(name = "turret")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String turret;
    /**
     * A tool storage mechanism that holds any number of tools. Tools are
     *               located in {{block(Pot)}}s. {{block(Pot)}}s are moved into
     *               position to transfer tools into or out of the
     *               {{block(ToolMagazine)}} by an {{block(AutomaticToolChanger)}}.
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "toolMagazine")
    @XmlAttribute(name = "toolMagazine")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String toolMagazine;
    /**
     * A linear or matrixed tool storage mechanism that holds any number
     *               of tools. Tools are located in {{block(Station)}}s.
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "toolRack")
    @XmlAttribute(name = "toolRack")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String toolRack;
    /**
     * The tool bar associated with a tool
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "toolBar")
    @XmlAttribute(name = "toolBar")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String toolBar;
    /**
     * A tool delivery mechanism that moves tools between a
     *               {{block(ToolMagazine)}} and a {{term(Spindle)}} a
     *               {{block(Turret)}}. An {{block(AutomaticToolChanger)}} may also
     *               transfer tools between a location outside of a piece of equipment
     *               and a {{block(ToolMagazine)}} or {{block(Turret)}}.
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "automaticToolChanger")
    @XmlAttribute(name = "automaticToolChanger")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String automaticToolChanger;

    /**
     * The tool location
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     * @see #getValue()
     */
    public void setValue(BigInteger value) {
        this.value = value;
    }

    /**
     * The type of location
     * 
     * @return
     *     possible object is
     *     {@link LocationsTypeType }
     *     
     */
    public LocationsTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationsTypeType }
     *     
     * @see #getType()
     */
    public void setType(LocationsTypeType value) {
        this.type = value;
    }

    /**
     * The number of location at lower index values from this location.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNegativeOverlap() {
        return negativeOverlap;
    }

    /**
     * Sets the value of the negativeOverlap property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     * @see #getNegativeOverlap()
     */
    public void setNegativeOverlap(BigInteger value) {
        this.negativeOverlap = value;
    }

    /**
     * The number of locations at higher index value from this location.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPositiveOverlap() {
        return positiveOverlap;
    }

    /**
     * Sets the value of the positiveOverlap property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     * @see #getPositiveOverlap()
     */
    public void setPositiveOverlap(BigInteger value) {
        this.positiveOverlap = value;
    }

    /**
     * A tool mounting mechanism that holds any number of tools. Tools
     *               are located in {{block(Station)}}s . Tools are positioned for use
     *               in the manufacturing process by rotating the {{block(Turret)}}.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTurret() {
        return turret;
    }

    /**
     * Sets the value of the turret property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getTurret()
     */
    public void setTurret(String value) {
        this.turret = value;
    }

    /**
     * A tool storage mechanism that holds any number of tools. Tools are
     *               located in {{block(Pot)}}s. {{block(Pot)}}s are moved into
     *               position to transfer tools into or out of the
     *               {{block(ToolMagazine)}} by an {{block(AutomaticToolChanger)}}.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToolMagazine() {
        return toolMagazine;
    }

    /**
     * Sets the value of the toolMagazine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getToolMagazine()
     */
    public void setToolMagazine(String value) {
        this.toolMagazine = value;
    }

    /**
     * A linear or matrixed tool storage mechanism that holds any number
     *               of tools. Tools are located in {{block(Station)}}s.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToolRack() {
        return toolRack;
    }

    /**
     * Sets the value of the toolRack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getToolRack()
     */
    public void setToolRack(String value) {
        this.toolRack = value;
    }

    /**
     * The tool bar associated with a tool
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToolBar() {
        return toolBar;
    }

    /**
     * Sets the value of the toolBar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getToolBar()
     */
    public void setToolBar(String value) {
        this.toolBar = value;
    }

    /**
     * A tool delivery mechanism that moves tools between a
     *               {{block(ToolMagazine)}} and a {{term(Spindle)}} a
     *               {{block(Turret)}}. An {{block(AutomaticToolChanger)}} may also
     *               transfer tools between a location outside of a piece of equipment
     *               and a {{block(ToolMagazine)}} or {{block(Turret)}}.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutomaticToolChanger() {
        return automaticToolChanger;
    }

    /**
     * Sets the value of the automaticToolChanger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getAutomaticToolChanger()
     */
    public void setAutomaticToolChanger(String value) {
        this.automaticToolChanger = value;
    }

}
