name: "Setup Nodejs environment"
description: "Setup Nodejs environment including all dependencies to execute runtime jobs"
inputs:
  working-directory:
    required: true
    description: move into the right directory
  run-install:
    description: Run the install pnpm command
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
      name: Install pnpm
      id: pnpm-install
      with:
        version: 11.14.0
        run_install: ${{ inputs.run-install }}

    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version: 24.16.0
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.yaml'

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm install --frozen-lockfile
