name: "Setup Nodejs environment"
description: "Setup Nodejs environment including all dependencies to execute runtime jobs"
inputs:
  working-directory:
    required: true
    description: move into the right directory
  run-install:
    description: Run the install pnpm command
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
      name: Install pnpm
      id: pnpm-install
      with:
        version: 8.4.0
        run_install: ${{ inputs.run-install }}

    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
      with:
        node-version: 18.16.0
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.yaml'

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm install --frozen-lockfile
