name: "Setup Nodejs environment"
description: "Setup Nodejs environment including all dependencies to execute runtime jobs"

runs:
  using: "composite"
  steps:
    - run: cd ${{ inputs.working_directory }}
      shell: bash

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 8.4.0
        run_install: false

    - uses: actions/setup-node@v3
      with:
        node-version: 18.16.0
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.json'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
