put:
  description: Add an adapter and all related parts like e.g. tags to the system.
  operationId: create-complete-adapter
  parameters:
    - description: The adapter type.
      in: path
      name: adaptertype
      required: true
      schema:
        type: string
    - description: The adapter name.
      in: path
      name: adaptername
      required: true
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/AdapterConfig.yaml
    description: The new adapter.
    required: true
  responses:
    '200':
      description: Success
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ProblemDetails.yaml
      description: Adapter failed validation
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ProblemDetails.yaml
      description: Adapter type not found
    '500':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ProblemDetails.yaml
      description: Internal Server Error
  summary: Add a new Adapter and all related parts like e.g. tags
  tags:
    - Protocol Adapters
