get:
  description: Obtain gateway configuration.
  operationId: get-xml-configuration
  responses:
    '200':
      content:
        application/xml:
          schema:
            type: string
      description: Success
    '405':
      content:
        application/xml:
          schema:
            $ref: ../components/schemas/ProblemDetails.yaml
      description: Error - function not supported
  summary: Obtain HiveMQ Edge Configuration
  tags:
    - Gateway Endpoint
