//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.hivemq.edge.adapters.mtconnect.schemas.devices.devices_2_4;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * {{block(Component)}} that observes the surroundings of another
 *         {{block(Component)}}. > Note: {{block(Environmental)}} **SHOULD** be
 *         organized by {{block(Auxillaries)}}, {{block(Systems)}} or
 *         {{block(Parts)}} depending on the relationship to the
 *         {{block(Component)}}.
 * 
 * <p>Java class for EnvironmentalType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="EnvironmentalType">
 *   <complexContent>
 *     <extension base="{urn:mtconnect.org:MTConnectDevices:2.4}CommonComponentType">
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@com.fasterxml.jackson.annotation.JsonTypeName(value = "EnvironmentalType")
@XmlType(name = "EnvironmentalType")
public class EnvironmentalType
    extends CommonComponentType
{


}
