//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.hivemq.edge.adapters.mtconnect.schemas.devices.devices_2_4;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * potential energy sources for the {{block(Component)}}.
 * 
 * <p>Java class for PowerSourceType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="PowerSourceType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <all>
 *         <element name="Order" type="{urn:mtconnect.org:MTConnectDevices:2.4}PowerSourceOrderType" minOccurs="0"/>
 *         <element name="Value" type="{urn:mtconnect.org:MTConnectDevices:2.4}PowerSourceValueType"/>
 *       </all>
 *       <attribute name="type" use="required" type="{urn:mtconnect.org:MTConnectDevices:2.4}PowerSourceTypeEnumType" />
 *       <attribute name="id" use="required" type="{urn:mtconnect.org:MTConnectDevices:2.4}IDType" />
 *       <attribute name="componentIdRef" type="{urn:mtconnect.org:MTConnectDevices:2.4}ComponentIdRefType" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@com.fasterxml.jackson.annotation.JsonTypeName(value = "PowerSourceType")
@XmlType(name = "PowerSourceType", propOrder = {

})
public class PowerSourceType {

    /**
     * optional precedence for a given power source
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "Order")
    @XmlElement(name = "Order")
    protected BigInteger order;
    /**
     * single data value that is expected to be reported for a
     *             {{block(DataItem)}}. {{property(Constraints::Value)}} **MUST NOT**
     *             be used in conjunction with any other {{block(Constraint)}}
     *             elements.
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "Value")
    @XmlElement(name = "Value", required = true)
    protected String value;
    /**
     * type of power source
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "type")
    @XmlAttribute(name = "type", required = true)
    protected PowerSourceTypeEnumType type;
    /**
     * identifier
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "id")
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    /**
     * reference to component
     * 
     */
    @com.fasterxml.jackson.annotation.JsonProperty(value = "componentIdRef")
    @XmlAttribute(name = "componentIdRef")
    @XmlIDREF
    protected Object componentIdRef;

    /**
     * optional precedence for a given power source
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     * @see #getOrder()
     */
    public void setOrder(BigInteger value) {
        this.order = value;
    }

    /**
     * single data value that is expected to be reported for a
     *             {{block(DataItem)}}. {{property(Constraints::Value)}} **MUST NOT**
     *             be used in conjunction with any other {{block(Constraint)}}
     *             elements.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getValue()
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * type of power source
     * 
     * @return
     *     possible object is
     *     {@link PowerSourceTypeEnumType }
     *     
     */
    public PowerSourceTypeEnumType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link PowerSourceTypeEnumType }
     *     
     * @see #getType()
     */
    public void setType(PowerSourceTypeEnumType value) {
        this.type = value;
    }

    /**
     * identifier
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getId()
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * reference to component
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getComponentIdRef() {
        return componentIdRef;
    }

    /**
     * Sets the value of the componentIdRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     * @see #getComponentIdRef()
     */
    public void setComponentIdRef(Object value) {
        this.componentIdRef = value;
    }

}
