name: OpenAPI validation

on:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    working-directory: ./hivemq-edge-openapi/

jobs:
  linting:
    name: OpenAPI specs linting
    runs-on: ubuntu-latest
    steps:
      - name: 👓 Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: 🏗️ Setup node environment
        uses: ./.github/actions/setup_node
        with:
          working-directory: ./hivemq-edge-openapi/

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest

      - name: Run linting
        run: redocly lint openapi/openapi.yaml --format=github-actions
