# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend - Visual Testing (Percy)

on:
  pull_request:
    branches: [master]
    paths:
      - hivemq-edge-frontend/**
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    if: false
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hivemq-edge-frontend/
    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - name: 👓 Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: 🚚 Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 8.4.0

      - name: 🔻 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🏗️ Build Application
        run: pnpm run build

      - name: 🧪 Run Cypress E2E
        uses: cypress-io/github-action@v6
        with:
          quiet: true
          working-directory: ./hivemq-edge-frontend/
          start: pnpm dev

      - name: 🧪 Run Cypress Component
        uses: cypress-io/github-action@v6
        with:
          quiet: true
          working-directory: ./hivemq-edge-frontend/
          component: true
          start: pnpm dev

      - name: 📸 Run Percy visual tests
        run: pnpm cypress:percy
        ## Percy should block the pipeline except if no money left on the plan :-)
        continue-on-error: true
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
