name: Publish EtherIP

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-check
  cancel-in-progress: true
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          repository: 'ornl-epics/etherip'
      - name: Setup Java
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: whelk-io/maven-settings-xml-action@9dc09b23833fa9aa7f27b63db287951856f3433d # v3.0.0
        with:
          servers: >
            [
              {
                "id":"github",
                "username":"${{ github.actor }}",
                "password":"${{ secrets.GITHUB_TOKEN }}"
              }
            ]
      - name: Build and Publish
        run: mvn package deploy:deploy-file -Durl=https://maven.pkg.github.com/hivemq/hivemq-edge -DrepositoryId=github -Dfile=target/etherip-1.0.0.jar -DpomFile=pom.xml
